### ISSUE TITLE
Notifications Emails being Sent on edit, sometimes multiple times after upgrade to 7.6.5

### ISSUE THREAD

**Issue by sojournerTim** [salesagility/SuiteCRM#1757]
#### Issue
I have 2 separate installations of SuiteCRM and after upgrading to 7.6.5 both are sending assignment email notifications when editing of a account/case/task occurs even if the editing was done by the owner. This is also reproduce-able when you edit something owned by another user. Sometimes these emails are sent multiple times. Highest I've had is around 10 I believe. This could be related to using inline editing and having that trigger the emails multiple times.

#### Expected Behavior
Assignment notifications should only go out when a new owner is assigned and should not go out multiple times (inline editing). Emails should never be sent when a user assigns something to themselves.

#### Actual Behavior
Assigment notifications are sent whenever something is edited even if assignment is not changed and even if you are already the owner.

#### Possible Fix
Unknown

#### Steps to Reproduce
1. Edit an account already assigned to you. Notification will be sent and say "YourUser has assigned an account to YourUser.
2. Edit something another user owns. They will receive a notification email saying that you assigned the object that you edited to them even though they were already the owner.

#### Context
Users are confused and think that new tasks are being assigned to them when they are not. I'd say this is medium to medium-high priority because it disrupts workflow.

#### Your Environment

* SuiteCRM Version used: 7.6.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 47.0.1, Chrome 51.0.2704.106 m
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6 I believe
* Operating System and version (e.g Ubuntu 16.04): CENTOS 7.2 x86_64

**Comment by samus-aran** [comment]
@sojournerTim Can you confirm if the issue is done to 'inline' editing?  That would be a great help to pinpoint that issue.

**Comment by sathishsengodan** [comment]
@sojournerTim I have added a fix that will not send emails when a user is assigns an account to himself, but will send emails if he assigns an account to someone else. With regards to multiple emails being sent out, we are looking in to this and will get back to you as soon as we the cause for it.

Thanks

**Comment by sojournerTim** [comment]
Awesome, also do you have any ideas on why it's sending the emails on every edit, even when assignment doesn't change? That's the one that is really flooding our email boxes right now. Thanks for the fast response!

**Comment by sathishsengodan** [comment]
You are welcome. One of the reasons I noticed was when you type in the user in the assigned to field through inline and save it without selecting it from the user's popup list or auto dropdown list, then it seems to send quite a few emails. But this will further investigation to find the root cause.

**Comment by sojournerTim** [comment]
Just wanted to update and say this fix does seem to have fixed some of the issues with emails but we are still getting assignment notification emails when someone edits a case/task that they don't own. Any ideas on a fix for this?

**Comment by sathishsengodan** [comment]
Hi @sojournerTim , please use the above fix instead of the previous one. I believe this should fix the issue completely and work as expected.

**Comment by sojournerTim** [comment]
Awesome. Just applied and will let you know if I see any issues.

**Comment by sojournerTim** [comment]
Sorry to say it did not fix it. I'm still getting occasional notification emails when someone edits a case that I own.

**Comment by sojournerTim** [comment]
The latest fix still did not correct the issue. 

Just to be clear again, this is happening not with inline editing but when you are editing a case via the full edit view. A user edits his/her own record and gets an email that they assigned the record to themselves.

Do I need to open a separate but report for that since it's different than what's been addressed here?

Thanks
