### ISSUE TITLE
Messed up Buttons with SuiteP Theme

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#1778]
#### Issue
The buttons in the detail views seem to be messed up.  I tested this in Chrome and Firefox. The issue appears in both browsers consistently. The chrome developer console does not show any errors. 

The buttons work fine, even the drop down. They only look strange. 

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17035749/e8334034-4f3d-11e6-8635-008624ac90da.png)

#### Your Environment
* SuiteCRM Version used: 7.7 RC
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 52 on Linux 64-bit
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by pgorod** [comment]
I've had a similar problem before, with the SuiteR theme. It's just a matter of column width.

I had done some changes in the labels, and I had switched to another font. So the word doesn't fit anymore in the assigned column space.

If you edit the layout to increase the % of column space available to those buttons, they won't "overflow" into a second row, and won't be as big (and ugly).

Of course, if this is happening for everyone, on the default setup, then it should be fixed in the "official" code.

**Comment by tfreier** [comment]
@pgorod Thank you for your input. Do you know where I would make those adjustments? I assume if I edit the themes files they will get overridden with upgrades.

**Comment by pgorod** [comment]
You can edit that in Studio, you don't need to change files. Edit the subpanels, the buttons appear there after all the columns. Their width is 5% by default (I think), just try 6% or more.

If you ever need to edit the themes, just copy the files over to the custom directory and that will be upgrade-safe. Google "suitecrm customizing themes" or "sugarcrm 6.5 customizing themes" to learn about it. Or buy Jim Mackin's book "SuiteCRM for Developers", that's the best resource out there (by far).

**Comment by tfreier** [comment]
@pgorod Thanks for the tip. I wasn't aware of that. However, that doesn't seem to fix the layout. Only after changing it from 5% to 20% I could see a difference: 

Before:

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17070036/af579df6-500e-11e6-86b5-afe4cb5d6578.png)

After:

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17070047/b70548c8-500e-11e6-98ac-3b3a4999b416.png)

**Comment by pgorod** [comment]
It looks like the two buttons (edit/remove) are on top of one another...

Sorry to get you to your starting point... this just looks like a bug in the theme...

**Comment by samus-aran** [comment]
@tfreier We are currently working on resolving the tweeks prior to Production release.  We'll keep this open until it has been addressed. :+1:

**Comment by tfreier** [comment]
It looks like the display issue has been resolved in 7.7RC2. The edit buttons appear normal now. However, the edit button do no longer appear to be drop downs. Is this how it's supposed to be? This only affects subpanel edit buttons.

**Comment by pgorod** [comment]
I can't test with RC2 now, but just to comment on what you said:
those buttons are supposed to be drop-downs when there is more than one option available (edit + remove), and they are not dropdowns when there is a single option available.

**Comment by tfreier** [comment]
@pgorod Thanks for the confirmation. So I can say for sure that the drop downs are not working anymore. 

These buttons work and look fine:

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17257407/d033a80e-5576-11e6-9ae1-471cb4e6332b.png)

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17257447/0ba25386-5577-11e6-8276-fc09fc822f7f.png)

However, the edit buttons don't drop down anymore. With the SuiteR theme I have a close option for the task:

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17257501/3b6d7e38-5577-11e6-8e19-6af2c7aeffd0.png)

**Comment by pgorod** [comment]
The following is what my rendered HTML looks like (as seen from Firefox's Inpector window) in theme SuiteR (where the dropdown appears correctly)

![dropdown](https://cloud.githubusercontent.com/assets/15945027/17258409/a16d31d2-55be-11e6-89fb-13c39a969db5.jpg)

Maybe you can compare that with the rendered HTML in SuiteP. I wonder if the buttons are there, only not showing (a problem of stylesheets), or if they are not there at all (a problem of page generation from the templates).

**Comment by tfreier** [comment]
The subnav seems to be there but does not appear.

![dashboard-add-order-recommendations1](https://cloud.githubusercontent.com/assets/1142090/17266488/caa784aa-55ad-11e6-91c7-dcf30b34805e.png)

**Comment by pgorod** [comment]
Aha! I spot something weird in your HTML. In the first `<ul>`, which is exactly the `sugaractionbutton` that is not showing in your theme (the small downward arrow to open the menu)... you have `== $0` to the right of that. 

Can you try removing that directly in the HTML inspector, just to see if that is in fact the culprit?

**Comment by samus-aran** [comment]
Hi Guys this should be resolved in the production release.

**Comment by vogelap** [comment]
The SuiteP theme has some issues... Dashboards don't appear, email address
fields are too short, and etc. It's pretty, but not completely functional
in my environment.

-drew
www.drewvogel.com

**Comment by pgorod** [comment]
@samus-aran sorry, but I installed Version 7.7 yesterday as soon as it came out, and this issue is still present. I get usable buttons - I can see a place to click and get it a drop-down with the other options; but the looks are all messed up (colors and relative positions of objects), much like the first screenshots in this issue. The dropdown button hardly looks like a button at all, it seems to be half-covered with something else.

It would help if the demo version of SuiteCRM can be updated to 7.7, that way we could compare our installation to the "standard" one to make sure the problems are not with our particular customizations. Thanks!

**Comment by tfreier** [comment]
I installed the update and can confirm that the bug has been fixed. Thank you!
