### ISSUE TITLE
Google Maps module - Not found error

### ISSUE THREAD

**Issue by normanu** [salesagility/SuiteCRM#3239]
When going to Geocode Adresses or trying to run the cron URL for jjwg_maps I get a not found error.

#### Issue
It is not updating the geocodes for the addresses.

#### Expected Behavior
I expect a positive result page and afterwords see in the counting the addresses as OK

#### Actual Behavior
I get a 404 Not Found error

#### Steps to Reproduce
1. Installed the system on IP address, at this point it still works
2. Changed config.php to the new domain address
3. Enabled https on the server
4. Added relations and contacts
5. Tried the cron and I get a 404 Not Found error.

#### Context
I want to geocode the addresses in the system to be able to make maps.
High priority

#### Your Environment
SuiteCRM Version used: Versie 7.8.2 Sugar / Versie 6.5.24 (Maken 509)
Browser name and version: Chrome Version 56.0.2924.87 (64-bit)
Environment name and version: MariaDB 10.1.21-r0, php5-5.6.30-r0
Operating System and version: Alpine Linux 3.5.2

**Comment by shogunpol** [comment]
@normanu , did you actually see 404 error? or is coming out white screen? Is this happen under https and http?

**Comment by chris001** [comment]
Probably related to issue #1007 and about 10 other issues posted here on github plus100 other community forum posts.
Good news is I've gotten the fix written and after testing plan to do a pull request for it today.

**Comment by normanu** [comment]
@shogunpol it is a 404 Not Found page, not a white screen.
The URL's not working, 
index.php?module=jjwg_Maps&action=geocode_addresses
index.php?module=jjwg_Maps&entryPoint=jjwg_Maps&cron=1

Also the iframe gives a 404 Not Found error when doing a Quick Radius map.

@chris001 does not seem related as I don't see any error in the logs, strangely enough.

This is the log while loading the geocode_addresses above,

[error.txt](https://github.com/salesagility/SuiteCRM/files/833653/error.txt)

**Comment by chris001** [comment]
Is it related to #3039 for the gif images (icons) missing ??

**Comment by normanu** [comment]
Hi @chris001 no this does not seem to be related.

**Comment by horus68** [comment]
@chris001 how about your pull request? Is it just for maps or for permissions?

> Good news is I've gotten the fix written and after testing plan to do a pull request for it today.

**Comment by chris001** [comment]
@normanu  Could you paste the exact text of the error message from the web sever error log, and from the php log.

**Comment by chris001** [comment]
@normanu  Is it a new install, after June 2016?  If yes, you need to add a Google Maps Geocoding API key, free for up to 25,000 addresses per day.
https://developers.google.com/maps/documentation/geocoding/start
Add the API key to the Admin "Google Maps Settings" page, in the box "Secret Phrase for Proxy".
`index.php?module=jjwg_Maps&action=config`

**Comment by horus68** [comment]
there is also this PR with an admin change so it will be easier to input the API key
Fixed - Error message in display maps. Added Google Maps API Key field https://github.com/salesagility/SuiteCRM/pull/2536

**Comment by normanu** [comment]
Even when adding the API key, the not found error remains.
The error log is above in in error.txt (https://github.com/salesagility/SuiteCRM/issues/3239#issuecomment-285636578)
There is no error in php-fpm.log

**Comment by chris001** [comment]
Try also #3290.  Are you able to install PR from the command line onto your server for the purpose of testing a solution to this issue?  If not, are you able to edit a few lines in the PHP files?

**Comment by normanu** [comment]
@chris001 I added &key=<api key> in the php files to the google url.
didn't fix it?

**Comment by chris001** [comment]
@normanu Can you provide more details about your system to the point where the bug can be reproduced as occurring on your system.  Shared or dedicated server, Server management software.  Installer used.  Subsequent commands used to modify the system, etc.

**Comment by chris001** [comment]
@normanu Can you try this command from the command line shell of your SuiteCRM Linux server:
`# curl https://maps.googleapis.com/maps/api/geocode/json?address=65+King+St,+Stirling+FK8+1DT,+UK`
See if it works or gives an error message.

**Comment by chris001** [comment]
@normanu 
Confirmed after testing.  Both a Google Maps Javascript API key (PR #2536),  and a Google Maps Geocoding API key (PR #3290) are needed, for the Maps module to work.

**Comment by samus-aran** [comment]
This looks like its been resolved the multiple PRs merged. If still an issue please request to be re-opened.
