### ISSUE TITLE
Subpanel column order is changed when i click next

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#3467]
#### Issue

When i click next in subpanel of modules, the order of column is changed.

**Before**
![screenshot_2](https://cloud.githubusercontent.com/assets/22373035/25470560/6c76011e-2b2b-11e7-94f8-0d074afb5234.png)
**After**
![screenshot_3](https://cloud.githubusercontent.com/assets/22373035/25470571/73b5ed5e-2b2b-11e7-9e5b-0b8791723cb5.png)

#### Expected Behavior

Column order should be same.
#### Steps to Reproduce

1. Open any module
2. Look at subpanel, it should be content more than 10.
3. Click next for other page
4. Look at the differences between first page and second page

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

**Comment by Dillon-Brown** [comment]
@dursuntosun I'm unable to replicate this on 7.8.3. The column order remains the same. Have you tried clearing the cache and repair/rebuild or replicating with a fresh instance?

**Comment by dursuntosun** [comment]
After applying this fix, it is occured.
[Fixed #3355](https://github.com/ale26/SuiteCRM/commit/26a51ca27fdc38cdbde1f380871c870d50773c44)

**Comment by dursuntosun** [comment]
Hi,
Why did you close it? The problem is continue:(

**Comment by Dillon-Brown** [comment]
@dursuntosun Ah sorry I might have misunderstood. Are you saying that the issue was caused by #3355 or that its still present before and after applying the fix?

**Comment by dursuntosun** [comment]
There are no this issue before applying #3355. After applying this fix, it occurs.

**Comment by Dillon-Brown** [comment]
@dursuntosun If the issue is a result of the proposed fix for #3355 then this wouldn't be a core issue. You'll need to raise it with @ale26 in #3356

**Comment by ale26** [comment]
I'm sorry for a lot of commits. They are all the same
There really only 1 commit. There was a problem with github, the commit was from another email address and the clahub did not accept this commit

**Comment by ale26** [comment]
The error did not occur due to damage to the Html structure (Issue #3355). After fixing the HTML structure was shown error #3467.

At the global level, the error lies in the fact that the SuiteP library uses the **footable** library. This library should not work in Suite7 and SuiteR, but [this fix](https://github.com/salesagility/SuiteCRM/commit/0cb92df6f66b5927a35d64a356f6f5c2e2e5d8b7) does not take this into account. After [applying this library](https://github.com/salesagility/SuiteCRM/commit/0cb92df6f66b5927a35d64a356f6f5c2e2e5d8b7) in Suite7 and SuiteR - it breaks the order of the columns.

**Comment by evgu** [comment]
Has this fix been propagated to 7.8.8 LTS branch? We still seem to be experiencing this 'pagination columns misalignment' issue in 7.8.8 on Suite 7 theme.

**Comment by ale26** [comment]
I fixed these errors, and created a pull request

But the developers modified my Pull-regest in such a way that the error was not corrected 
( [pull request](https://github.com/salesagility/SuiteCRM/pull/3356) )

The developers asked to check, I checked, wrote about the fact that their option will not work.

To date, the problem remains open and there is no desire to make changes again. Tickets are not considered for a very long time, often the new kernel code breaks existing functionality. I decided to give up SuiteCRM in my projects.

**Comment by ale26** [comment]
I will give the decision within 2 days...

**Comment by evgu** [comment]
@Dillon-Brown, @daniel-samson, This issue has been marked as closed but the bug is still there and impacting LTS now for several months (e.g. we are on Suite 7 theme, v7.8.8 LTS). This heavily impacts usability of SuiteCRM on Suite 7 theme, as user has to reload the page after each history-page-next, in order to be able to clearly see the record's history. 

There seems to be a lot of ping-pong on this thread. @ale26 says he has proposed a solution, but it was not accepted. Please reopen and move this bug to the correct thread/branch, so it can be picked up and solved in the LTS branch.
