### ISSUE TITLE
Inbound Emails throws Error (7.9)

### ISSUE THREAD

**Issue by tfreier** [salesagility/SuiteCRM#3483]
When opening inbound emails under Activities>Emails the page is blank. In the apache error log I was able to locate the following error. 

#### Issue
`PHP Fatal error:  Uncaught Error: Call to a member function checkWithPagination() on boolean in /var/www/crm/public_html/modules/Emails/include/ListView/ListViewDataEmails.php:280\nStack trace:\n#0 /var/www/crm/public_html/modules/Emails/include/ListView/ListViewSmartyEmails.php(118): ListViewDataEmails->getListViewData(Object(Email), '', 0, -1, Array, Array, 'id', true, NULL)\n#1 /var/www/crm/public_html/include/MVC/View/views/view.list.php(201): ListViewSmartyEmails->setup(Object(Email), 'include/ListVie...', '', Array)\n#2 /var/www/crm/public_html/include/MVC/View/views/view.list.php(294): ViewList->listViewProcess()\n#3 /var/www/crm/public_html/include/MVC/View/SugarView.php(169): ViewList->display()\n#4 /var/www/crm/public_html/include/MVC/Controller/SugarController.php(363): SugarView->process()\n#5 /var/www/crm/public_html/include/MVC/Controller/SugarController.php(310): SugarController->processView()\n#6 /var/www/crm/public_html/include/MVC/SugarApplication.php(105): SugarController->execute()\n#7 /var/www/crm/public_html/index in /var/www/crm/public_html/modules/Emails/include/ListView/ListViewDataEmails.php on line 280`

#### Steps to Reproduce

Go to Activities > Emails

#### Context

This prevents users from using inbound emails within SuiteCRM. Therefore I would give this a high priority. 

#### Your Environment

* SuiteCRM Version used: 7.9-beta
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Linux Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.1.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 LTS

**Comment by tfreier** [comment]
It appears like the following line is returning false which is not expected.
modules/Emails/include/ListView/ListViewDataEmails.php:
`$inboundEmail = BeanFactory::getBean('InboundEmail', $inboundEmailID);
`
The inboundEmailID is a valid UUID but I am not able to find it in the inbound email table.

**Comment by daniel-samson** [comment]
@tfreier I have checked this in the release candidate. I looks like this issue has been resolved. Can you please test the release candidate to confirm that this issue has been resolved?

**Comment by tfreier** [comment]
I just installed the RC version and the page looks slightly different but is still broken. 
![email-bug](https://cloud.githubusercontent.com/assets/1142090/25877817/e11d8862-34da-11e7-832e-909ab8607955.png)

**Comment by samus-aran** [comment]
Hi @tfreier - Can you confirm your group Emails have been set up via your User Profile > Email Settings (it has been moved to its new place)?

Please provide full steps on how you can replicate the issue.  From your current steps there is no indication that Group Emails were set up, or if you are using your personal email.

A screenshot of those settings would be much appreciated (though de-sensitise it).

**Comment by tfreier** [comment]
@samus-aran That's good to know. They had been set up before but not in the new version. I'll check this out later today.

**Comment by tfreier** [comment]
Is there anything else I can try? I just tried messing around with it a bit more but I don't know where to go from here. There is nothing in the logs. Clearing browser cache and cookies doesn't help either.

**Comment by tfreier** [comment]
@samus-aran I think the pending input tag can be removed at this point unless there is anything else I can provide.

**Comment by tfreier** [comment]
So since 7.9 was released now I tried it again with the release version. Same issue but I noticed some php notices. 
`[Thu Jun 01 17:22:17.976752 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: bean in /home/till/workspace/php/public_html/include/ListView/ListViewDisplay.php on line 218, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.976788 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 145, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.976792 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 145, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.976795 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 146, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.976798 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 150, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.976968 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 151, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.983150 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: ordering in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 178, referer: http://localhost/php/public_html/index.php?module=Home&action=About
[Thu Jun 01 17:22:17.983199 2017] [:error] [pid 25149] [client 127.0.0.1:33778] PHP Notice:  Undefined index: offsets in /home/till/workspace/php/public_html/include/ListView/ListViewSmarty.php on line 238, referer: http://localhost/php/public_html/index.php?module=Home&action=About`

 Any help is much appreciated!

**Comment by Mausino** [comment]
@tfreier i think it has somehing similary with those bugs #3615 and #3629 because i see that you added there group email account. Same issue is persisting on my site :(

**Comment by tfreier** [comment]
Thanks @Mausino, I'm glad I'm not the only one with this issue. Let me know if there's anything I can do to help. I was really looking forward to an improved email management in SuiiteCRM.

**Comment by samus-aran** [comment]
Hi @tfreier Is this specific to Group Inbound Emails yes?  So you have no personal accounts and ONLY Group?

Just so I can rephrase the Title of the issue.

**Comment by tfreier** [comment]
@samus-aran, that is correct. We only use a group email account.

**Comment by samus-aran** [comment]
This should be resolved in the next release.
