### ISSUE TITLE
Scheduled reports detail view broken - cannot redeclare padNumbers

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3604]
When testing something for someone on the forums I ran into a couple of bugs in Scheduled reports: a menu bug and a broken screen bug.

#### Issue and Steps to Reproduce
1. Open the SuiteCRM 7.8.3 online demo, for example
2. Go into Reports module and create a report called "Test report". I selected the Leads module for this report, and didn't set anything else. Hit Save.
3. Go into the `All` menu and select the `Scheduled Reports` module. Wait, the option is not there for some reason... **this is a first bug**.
4. Work around it by editing the URL to be 
```
https://demo.suiteondemand.com/index.php?module=AOR_Scheduled_Reports&action=index
```
5. Now create a new Scheduled report called "Test Scheduled Report", select the report "Test Report", and use `Daily, 7:00` for a schedule time. Hit Save.

#### Expected Behavior
It should save correctly and show me the detail view of the new Scheduled Report.

#### Actual Behavior
Kaboom!
![brokenreports](https://cloud.githubusercontent.com/assets/15945027/26520434/6d1f7ecc-42ca-11e7-8e48-cc12d412c733.JPG)

A further step to this bug is if you go to the Scheduled Reports list view, the new Scheduled report is there, but if you click on it, you get another error:

![brokenreports2](https://cloud.githubusercontent.com/assets/15945027/26520450/ad667e86-42ca-11e7-9d62-14a5ec4ac9a9.JPG)

#### Logs
The php_errors.log looks the same for both screenshots, only in one of the situation the error is caught, in the other it breaks the page.
```
[27-May-2017 11:16:53 Europe/Lisbon] PHP Fatal error:  Cannot redeclare padNumbers() (previously declared in /var/www/html/include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.php:41) in /var/www/html/include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.php on line 41
[27-May-2017 11:16:53 Europe/Lisbon] PHP Stack trace:
[27-May-2017 11:16:53 Europe/Lisbon] PHP   1. {main}() /var/www/html/index.php:0
[27-May-2017 11:16:53 Europe/Lisbon] PHP   2. SugarApplication->execute() /var/www/html/index.php:52
[27-May-2017 11:16:53 Europe/Lisbon] PHP   3. SugarController->execute() /var/www/html/include/MVC/SugarApplication.php:105
[27-May-2017 11:16:53 Europe/Lisbon] PHP   4. SugarController->processView() /var/www/html/include/MVC/Controller/SugarController.php:310
[27-May-2017 11:16:53 Europe/Lisbon] PHP   5. SugarView->process() /var/www/html/include/MVC/Controller/SugarController.php:364
[27-May-2017 11:16:53 Europe/Lisbon] PHP   6. ViewDetail->display() /var/www/html/include/MVC/View/SugarView.php:169
[27-May-2017 11:16:53 Europe/Lisbon] PHP   7. EditView->display() /var/www/html/include/MVC/View/views/view.detail.php:104
[27-May-2017 11:16:53 Europe/Lisbon] PHP   8. TemplateHandler->displayTemplate() /var/www/html/include/EditView/EditView2.php:707
[27-May-2017 11:16:53 Europe/Lisbon] PHP   9. TemplateHandler->buildTemplate() /var/www/html/include/TemplateHandler/TemplateHandler.php:316
[27-May-2017 11:16:53 Europe/Lisbon] PHP  10. Sugar_Smarty->fetch() /var/www/html/include/TemplateHandler/TemplateHandler.php:155
[27-May-2017 11:16:53 Europe/Lisbon] PHP  11. Smarty->fetch() /var/www/html/include/Sugar_Smarty.php:131
[27-May-2017 11:16:53 Europe/Lisbon] PHP  12. include() /var/www/html/include/Smarty/Smarty.class.php:1264
[27-May-2017 11:16:53 Europe/Lisbon] PHP  13. Smarty->_smarty_include() /var/www/html/cache/smarty/templates_c/%%0D^0D2^0D28DA69%%DetailView.tpl.php:400
[27-May-2017 11:16:53 Europe/Lisbon] PHP  14. include() /var/www/html/include/Smarty/Smarty.class.php:1870
[27-May-2017 11:16:53 Europe/Lisbon] PHP  15. smarty_function_sugar_field() /var/www/html/cache/smarty/templates_c/%%1C^1CB^1CB7D149%%tab_panel_content.tpl.php:203
[27-May-2017 11:16:53 Europe/Lisbon] PHP  16. SugarFieldHandler::displaySmarty() /var/www/html/include/Smarty/plugins/function.sugar_field.php:104
[27-May-2017 11:16:53 Europe/Lisbon] PHP  17. SugarFieldBase->getDetailViewSmarty() /var/www/html/include/SugarFields/SugarFieldHandler.php:166
[27-May-2017 11:16:53 Europe/Lisbon] PHP  18. SugarFieldBase->getSmartyView() /var/www/html/include/SugarFields/Fields/Base/SugarFieldBase.php:183
[27-May-2017 11:16:53 Europe/Lisbon] PHP  19. SugarFieldCronSchedule->setup() /var/www/html/include/SugarFields/Fields/Base/SugarFieldBase.php:144
```

#### Your Environment
* SuiteCRM Version used: 7.8.3 online demo
* Browser name and version: Firefox 53
* Environment name and version: SalesAgility online demo 
* Operating System and version: SalesAgility online demo

**Comment by pgorod** [comment]
Using
```
        if (!function_exists('padNumbers'))   {
                function padNumbers($x){
                    return str_pad($x,2,'0',STR_PAD_LEFT);
                }
        }
```
fixes the error, I just don't know if that is the proper solution or something better could be done.

**Comment by Dillon-Brown** [comment]
@pgorod I can't seem to confirm your first issue. Scheduled reports is hidden by default on the 'ALL' menu. Are you sure that it was set to be visible before you created the report?

Second part of your issue confirmed as a bug.

**Comment by pgorod** [comment]
Hello @Dillon-Brown. I was a bit confused about the menu options when I wrote that. I tried it on my own system, and then went to the online demo to confirm it, and only noticed the menu issue there.

It seems the option is hidden except for Administrators, can you confirm that is the case?

But then it seems there is some incoherence: if it is not in the menu for non-admins, then perhaps it shouldn't be possible to access it just by typing in the URL...

Thanks.

**Comment by Dillon-Brown** [comment]
@pgorod The menu option for scheduled reports is hidden for all users (including admin) unless the administrator goes into "display modules and sub-panels" in the admin panel and sets it to be visible system wide. 

By having the module set to "hidden" it will not appear on the "all" menu but users can still access it directly. To control access to modules, you would want to use role management.

**Comment by pgorod** [comment]
Ok, I understand the logic now. Thanks.

So we're left with the central issue then. I would say there are two separate things to fix, though:

1. While PHP is throwing the error, we should fix the way it breaks the display when saving, so that a proper message is shown.
2. Fix the error itself.

Do you understand why/how this is being included twice? I couldn't find the includes/requires... I tried searching for parts of `include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.php` (because the string to include may be composed by concatenation at runtime) but still couldn't find it...

**Comment by chris001** [comment]
Let's fix this by merging #3237 and replace all these problem-prone `include` and `require` with the PSR-4 autoloader's `use`.

**Comment by sanchezfauste** [comment]
This error is still present on 7.8.8 LTS version. It would be interesting to fix it, since it is not possible to open the detailed view of Scheduled Reports.

**Comment by dflois** [comment]
Another possible fix maybe:
		$padNumbers= function($x){
			return str_pad($x,2,'0',STR_PAD_LEFT);
		};
		$minutes = array_map($padNumbers,range(0,59));
		$hours = array_map($padNumbers,range(0,23));

The scope of this variable should be the current function.

**Comment by vmijalkovic** [comment]
This issue is still with us. 
v 7.10.1

**Comment by sanchezfauste** [comment]
I think that #5443 shoud fix the issue.

**Comment by pgorod** [comment]
@sanchezfauste I guess you are right, I just tried this on 7.10.4 and it seems to be working.

@Dillon-Brown I think you can close. Thanks
