### ISSUE TITLE
popup search for documents in mail compose not working

### ISSUE THREAD

**Issue by marcoblancas** [salesagility/SuiteCRM#3737]
#### Issue
The popup search filter for documents in suitecrm when you compose a mail is not working an always list all the documents in suitecrm.

#### Expected Behavior
The listed documents should match with the filters applied by the user.

#### Actual Behavior
All documents in suitecrm are listed.

#### Possible Fix
???? not a programer

#### Steps to Reproduce
1. Be sure at least you have one document created
2. Compose an email
3. Click on the right bar for attachments an templates
4. ADD DOCUMENT (From SuiteCRM)
5. Click in arrow
6. Filter with a name document you haven't ('kkkkkkkkkkk')
7. SEARCH

![areadetrabajo1626](https://user-images.githubusercontent.com/5545390/27248591-11f38394-5306-11e7-9044-80c6d4d530db.png)

#### Context
Actually we have thousand of documents and user can't find the documents they want to attach. They must go to the Documents module, search the document, download lo local and attach it in the mail using the ADD FILE (From local System). No way to attach files when they are on mobile.

#### Your Environment
* SuiteCRM Version used: 7.8.5
* Browser name and version: Versión 58.0.3029.110 (64-bit) (e.g. Chrome Version 51.0.2704.63 (64-bit))
* Environment name and version:  5.6.33
* Operating System and version: 16.04

**Comment by marcoblancas** [comment]
The problem is with the url used to load de pop-up window. It's refering to the "Emails" module and it should be referenced to the "Documents" module. 

Now, in 7.8.5 it uses:
http://localhost/SuiteCRM/index.php?module=**Emails&action=PopupDocuments&to_pdf=true&target=0**

And 9.0.1 uses
http://localhost/SuiteCRM/index.php?module=**Documents&action=Popup&mode=single&create=false&field_to_name[]=name**
![areadetrabajo1627](https://user-images.githubusercontent.com/5545390/27252231-3dc744f8-5359-11e7-9138-4024c5d311f5.png)

**Comment by pgorod** [comment]
@marcoblancas you're right that the URL has changed, but that isn't necessarily the problem because this is all quite changed, there's a lot of new code.  Can you check your logs at the moment of the failed Search? Maybe there are clues there.

**Comment by marcoblancas** [comment]
This is the log I get when  I click on the search button in the pop-up-
`Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] current_language is: en_us
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheRedis
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheMemory
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Using cache backend SugarCacheMemory, since 999 is less than 1000
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheFile
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheZend
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheMemcached
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheWincache
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheAPC
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Using cache backend SugarCacheAPC, since 940 is less than 999
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCachesMash
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Found cache backend SugarCacheMemcache
Sat Jun 17 14:34:25 2017 [20251][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Berlin. Please set date.timezone="Europe/Berlin" in php.ini!
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] rebuilding cache for Users
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Users' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.00025606155395508
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] rebuilding cache for Employees
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Employees' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.0002601146697998
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] rebuilding cache for EmailAddresses
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='EmailAddresses' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.00031089782714844
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] rebuilding cache for UserPreferences
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='UserPreferences' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.0002129077911377
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] rebuilding cache for Administration
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Administration' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.00020503997802734
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Hook called: ::after_entry_point
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Including module specific hook file for custom/modules
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Including Ext hook file for custom/application
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Hook called: ::after_session_start
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] We have an authenticated user id: 1
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Hook called: Users::before_retrieve
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Including module specific hook file for custom/modules/Users
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Retrieve User : SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0
Sat Jun 17 14:34:25 2017 [20251][-none-][DEBUG] Limit Query:SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 Start: 0 count: 1
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query:SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1
Sat Jun 17 14:34:25 2017 [20251][-none-][INFO] Query Execution Time:0.00030088424682617
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT u1.first_name, u1.last_name from users  u1, users  u2 where u1.id = u2.reports_to_id AND u2.id = '1' and u1.deleted=0
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00017690658569336
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[User].load_relationships, Loading relationship (reports_to_link).
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT ea.email_address, ea.email_address_caps, ea.invalid_email, ea.opt_out, ea.date_created, ea.date_modified,
                ear.id, ear.email_address_id, ear.bean_id, ear.bean_module, ear.primary_address, ear.reply_to_address, ear.deleted
                FROM email_addresses ea LEFT JOIN email_addr_bean_rel ear ON ea.id = ear.email_address_id
                WHERE ear.bean_module = 'Users'
                AND ear.bean_id = '1'
                AND ear.deleted = 0
                ORDER BY ear.reply_to_address, ear.primary_address DESC
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00036406517028809
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Hook called: Users::after_retrieve
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Current user is: admin
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Current user is: admin
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] setting cookie ck_login_id_20 to 1
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] setting cookie ck_login_language_20 to en_us
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] current_language is: en_us
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] rebuilding cache for Emails
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Emails' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00029706954956055
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Module:Emails using file: PopupDocuments
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Here is the where clause for the list view: 
Sat Jun 17 14:34:25 2017 [20251][1][WARN] CSS File yui.css not found
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] rebuilding cache for Documents
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Documents' AND  deleted = 0
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00031590461730957
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (modified_user_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (created_by_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (assigned_user_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] get_list:  order_by = 'document_name asc' and where = 'documents.doc_type IN ( '', 'Sugar')' and limit = ''
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (modified_user_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (created_by_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] SugarBean[Document].load_relationships, Loading relationship (assigned_user_link).
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] process_list_query:  SELECT  documents.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM documents   LEFT JOIN  users jt0 ON documents.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON documents.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON documents.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (documents.doc_type IN ( '', 'Sugar')) AND documents.deleted=0 ORDER BY documents.document_name asc
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query: SELECT count(*) c FROM documents   LEFT JOIN  users jt0 ON documents.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON documents.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON documents.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (documents.doc_type IN ( '', 'Sugar')) AND documents.deleted=0
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00034689903259277
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Limit Query: SELECT  documents.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM documents   LEFT JOIN  users jt0 ON documents.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON documents.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON documents.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (documents.doc_type IN ( '', 'Sugar')) AND documents.deleted=0 ORDER BY documents.document_name asc Start: 0 count: 20
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query: SELECT  documents.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM documents   LEFT JOIN  users jt0 ON documents.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON documents.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON documents.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (documents.doc_type IN ( '', 'Sugar')) AND documents.deleted=0 ORDER BY documents.document_name asc LIMIT 0,20
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00029611587524414
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): id = 6f6e4101-b842-f7db-cd2c-594472a5cbde
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): date_entered = 2017-06-17 00:08:02
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): date_modified = 2017-06-17 00:08:02
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): modified_user_id = 1
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): modified_by_name = admin
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): created_by = 1
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): created_by_name = admin
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): description = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): deleted = 0
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): assigned_user_id = 1
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): assigned_user_name = admin
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): document_name = SEscaner MC17060516370.pdf
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): doc_id = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): doc_type = Sugar
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): doc_url = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): active_date = 2017-06-17
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): category_id = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): subcategory_id = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): status_id = Active
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): document_revision_id = 7094daf4-4e78-2326-c85e-594472490ab9
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): related_doc_id = 
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): is_template = 0
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Document(6f6e4101-b842-f7db-cd2c-594472a5cbde): template_type = 
Sat Jun 17 14:34:25 2017 [20251][1][WARN] Image _image_inline.gif not found
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT users.first_name AS first_name, users.last_name AS last_name, document_revisions.date_entered AS rev_date,
            	 document_revisions.filename AS filename, document_revisions.revision AS revision,
            	 document_revisions.file_ext AS file_ext, document_revisions.file_mime_type AS file_mime_type
            	 FROM users, document_revisions
            	 WHERE users.id = document_revisions.created_by AND document_revisions.id = '7094daf4-4e78-2326-c85e-594472490ab9'
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00023102760314941
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Hook called: Documents::process_record
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Offsets: (start, previous, next, last)(0, -20, 20, 0)
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Offset (next, current, prev)(20, 0, -20)
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Start/end records (1, 2)
Sat Jun 17 14:34:25 2017 [20251][1][WARN] Image _image_inline.gif not found
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query:SELECT users.first_name AS first_name, users.last_name AS last_name, document_revisions.date_entered AS rev_date,
            	 document_revisions.filename AS filename, document_revisions.revision AS revision,
            	 document_revisions.file_ext AS file_ext, document_revisions.file_mime_type AS file_mime_type
            	 FROM users, document_revisions
            	 WHERE users.id = document_revisions.created_by AND document_revisions.id = '7094daf4-4e78-2326-c85e-594472490ab9'
Sat Jun 17 14:34:25 2017 [20251][1][INFO] Query Execution Time:0.00027990341186523
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Hook called: Emails::after_ui_frame
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Including module specific hook file for custom/modules/Emails
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Creating new instance of hook class hooks without parameters
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Creating new instance of hook class AssignGroups without parameters
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Hook called: ::after_ui_footer
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Creating new instance of hook class AssignGroups without parameters
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Hook called: ::server_round_trip
Sat Jun 17 14:34:25 2017 [20251][1][DEBUG] Calling MySQLi::disconnect()
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] current_language is: en_us
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheRedis
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheMemory
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Using cache backend SugarCacheMemory, since 999 is less than 1000
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheFile
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheZend
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheMemcached
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheWincache
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheAPC
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Using cache backend SugarCacheAPC, since 940 is less than 999
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCachesMash
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Found cache backend SugarCacheMemcache
Sat Jun 17 14:34:27 2017 [19868][-none-][FATAL] Configuration variable date.timezone is not set, guessed timezone Europe/Berlin. Please set date.timezone="Europe/Berlin" in php.ini!
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] rebuilding cache for Users
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Users' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.00022101402282715
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] rebuilding cache for Employees
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Employees' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.00019311904907227
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] rebuilding cache for EmailAddresses
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='EmailAddresses' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.00027298927307129
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] rebuilding cache for UserPreferences
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='UserPreferences' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.00019001960754395
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] rebuilding cache for Administration
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Administration' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.0001978874206543
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Hook called: ::after_entry_point
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Including module specific hook file for custom/modules
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Including Ext hook file for custom/application
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Hook called: ::after_session_start
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] We have an authenticated user id: 1
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Hook called: Users::before_retrieve
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Including module specific hook file for custom/modules/Users
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Retrieve User : SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0
Sat Jun 17 14:34:27 2017 [19868][-none-][DEBUG] Limit Query:SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 Start: 0 count: 1
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query:SELECT users.* FROM users  WHERE users.id = '1' AND users.deleted=0 LIMIT 0,1
Sat Jun 17 14:34:27 2017 [19868][-none-][INFO] Query Execution Time:0.00027203559875488
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query:SELECT u1.first_name, u1.last_name from users  u1, users  u2 where u1.id = u2.reports_to_id AND u2.id = '1' and u1.deleted=0
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query Execution Time:0.00019001960754395
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] SugarBean[User].load_relationships, Loading relationship (reports_to_link).
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query:SELECT ea.email_address, ea.email_address_caps, ea.invalid_email, ea.opt_out, ea.date_created, ea.date_modified,
                ear.id, ear.email_address_id, ear.bean_id, ear.bean_module, ear.primary_address, ear.reply_to_address, ear.deleted
                FROM email_addresses ea LEFT JOIN email_addr_bean_rel ear ON ea.id = ear.email_address_id
                WHERE ear.bean_module = 'Users'
                AND ear.bean_id = '1'
                AND ear.deleted = 0
                ORDER BY ear.reply_to_address, ear.primary_address DESC
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query Execution Time:0.00054693222045898
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Hook called: Users::after_retrieve
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Current user is: admin
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Current user is: admin
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] setting cookie ck_login_id_20 to 1
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] setting cookie ck_login_language_20 to en_us
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] current_language is: en_us
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] rebuilding cache for Alerts
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query:SELECT * FROM fields_meta_data WHERE  custom_module='Alerts' AND  deleted = 0
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query Execution Time:0.00028204917907715
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Performing action: action_get MODULE: Alerts
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] get_full_list:  order_by = 'alerts.date_entered' and where = 'alerts.assigned_user_id = '1' AND is_read != '1''
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] SugarBean[Alert].load_relationships, Loading relationship (modified_user_link).
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] SugarBean[Alert].load_relationships, Loading relationship (created_by_link).
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] SugarBean[Alert].load_relationships, Loading relationship (assigned_user_link).
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] process_order_by: (alerts.date_entered) does not have a vardef entry.
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] process_full_list_query: query is  SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0

 AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0

 AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0
Sat Jun 17 14:34:27 2017 [19868][1][INFO] Query Execution Time:0.00033307075500488
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] process_full_list_query: result is mysqli_result Object
(
    [current_field] => 0
    [field_count] => 22
    [lengths] => 
    [num_rows] => 0
    [type] => 0
)

Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Hook called: ::server_round_trip
Sat Jun 17 14:34:27 2017 [19868][1][DEBUG] Calling MySQLi::disconnect()
`

**Comment by pgorod** [comment]
(it's better if you put this kind of long output inside lines with three back-ticks ` ``` `, this way it will get a nice scroll-bar. Put the 3 back-ticks in one line, then the text, then a line with 3 more back-ticks to finish it. You can edit your post to fix it now, if you want)

You should start by fixing those timezone errors. With FATAL errors, you never know what you're breaking in the app. So you always need to fix them before you attempt any other troubleshooting.

So edit both your `php.ini`'s (the web server one, and the CLI one) and add timezone, then check your issue again, and the logs. If you don't know anything about this you can read [an explanation here](https://pgorod.github.io/Scheduler-Jobs/) (in the section about `php.ini`).

**Comment by marcoblancas** [comment]
Thank you @pgorod

I have solved the FATAL errors related with the timezone. In my previous comment I have updated the new log, now with the back-ticks ;-) , but there are no ERRORS.

**Comment by pgorod** [comment]
Well it seems those errors weren't related, then. Do you see your search string anywhere in that log? Did you use "kkkkkkk" that time?

I'm sorry, I can't make much progress here because in my test system I can't even open that Documents pop-up. I am stuck in a previous error!

Let's hope somebody else can reproduce this and debug it...

**Comment by marcoblancas** [comment]
No... in the log there's nothing related with 'kkkk...' and it was the name I used for the document in the pop-up.

**Comment by Dillon-Brown** [comment]
@marcoblancas This has been resolved for 7.9.1. It looks like this is a much older bug not something new introduced in 7.8.5.

**Comment by pgorod** [comment]
@Dillon-Brown which PR solves this for 7.9.1? 

On 7.9.1, I have applied the fix #3752 (it seemed related) and now finally I can open the Documents pop-up, but I do still get the bug reported in this issue. If I search, I can't get the selection on the pop-up to be passed down to the window underneath...

**Comment by Dillon-Brown** [comment]
@pgorod This issue was only related to being unable to search with the documents popup. This should be fixed in 7.9.1 hotfix.:
![3737_1](https://user-images.githubusercontent.com/26431166/27387820-ab91c1ee-5691-11e7-9b99-2a246aa1b034.png)


Searching for non-existing document:
![3737_2](https://user-images.githubusercontent.com/26431166/27387822-adc2dbd8-5691-11e7-8991-a6f87d4329c1.png)

I can confirm your issue on my end as well. I'll raise a separate issue for not being able to select a document after doing a search.

**Comment by pgorod** [comment]
Ok, I thought this was just one problem, but you're right. Thanks

**Comment by marcoblancas** [comment]
I have a fix but somebody should review this...

You can review at https://github.com/marcoblancas/SuiteCRM/commit/49fc7df40ab694e351d3ff555f86a5de91534fe2

The popup documents works OK when composing *Email Template* so I have used the code in the PopupDocumentsCampaignTemplate.php in the EmailTemplate module to replace the PopupDocuments.php in the Email module with a minimun change.

Tested in my local environment with 7.8.5 seems to be working OK.

As @Dillon-Brown wrote... the problem was present in previous releases... I've been reported from 7.6.7

**Comment by pgorod** [comment]
@marcoblancas about those three lines, the comment says:

> We can't attach remote documents to emails because we can't necessarialy fetch a copy of them to include.

I don't know _exactly_ what this means, but I can see that there is a type of Document called "remote document", and that is something that you don't have available on your server, so you can't attach to an email. So I would say it's probably lacking in the `EmailTemplates` module, instead of being something we can just drop from the `Emails` module.

I'm following [Chesterton's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) principle here: if we don't know why it's there, we don't take it down.

But perhaps somebody knows exactly what these "remote documents" are, and can shed some light here?

**Comment by marcoblancas** [comment]
Maybe you are right. These lines were included in sugarCRM 6.2.0 in this commit but no more clues about what it means. https://github.com/sugarcrm/sugarcrm_dev/commit/a84f4a930b0ca7e79f37cbef041669203c13829b#diff-d72c77f05e3be1d1bee77a0bbf7b65c5

Some body knows what's "remote documents".

**Comment by kingzfn** [comment]
Thanks for the fix. Is there any way to change the search parameters on this screen? Changing the popup search options in Studio doesn't seem to have any effect on this screen using Version 7.7.9

**Comment by marcoblancas** [comment]
As far as I know there's no way to custom this pop-up with studio. That could be a new feature for 7.9.x...
