### ISSUE TITLE
Send offer/invoice as PDF -> Document not attached to email

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3787]
Upgraded 7.8.4 to 7.91.
Unable to send offers or invoices as PDF via mail.

#### Issue
Unable to send offers or invoices as PDF via mail.
Getting white screen and the following errors:

`06/26/17 15:10:30 [8096][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL] Exception in Controller: Es gibt keine Aktion mit diesem Namen.
06/26/17 15:10:30 [8096][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL] backtrace:
#0 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(551): sugar_die('Es gibt keine A...')
#1 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(1086): SugarController->no_action()
#2 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(460): SugarController->handleActionMaps()
#3 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(366): SugarController->process()
#4 C:\inetpub\suitecrm\include\MVC\SugarApplication.php(105): SugarController->execute()
#5 C:\inetpub\suitecrm\index.php(52): SugarApplication->execute()`

I overwrote some code that replaces "Compose" with "ComposeView" but it breaks a whole lot of other stuff.

#### Expected Behavior
Open Compose Window with attached PDF

#### Actual Behavior

White Screen

#### Steps to Reproduce

1. Open invoice
2. Click Send PDF via Mail (or whatever it is in your language)
3. Choose template
4. White Screen

#### Context
High priority as it breaks most of our workflows. Will roll back.

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52 and Chrome 58
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP 7
* Operating System and version (e.g Ubuntu 16.04): Windows Server with IIS

**Comment by ChangezKhan** [comment]
Yes, I am able to recreate the scenario. It's a bug.

**Comment by Dillon-Brown** [comment]
@halest  @ChangezKhan The fix here should resolve this issue: https://github.com/salesagility/SuiteCRM/pull/3748

**Comment by halest** [comment]
Hey @Dillon-Brown , thanks for the input. I have applied the diff from the attached commit and am not getting a white screen. But the created PDF is still not attached to the E-Mail. Anything else I'd need to change?

**Comment by halest** [comment]
@Dillon-Brown Though I cannot choose an outgoing E-Mail-Account any more. List is empty

**Comment by Dillon-Brown** [comment]
@halest Confirmed as a bug. Can you modify the title for the created PDF is still not attached to the E-Mail?

**Comment by Dillon-Brown** [comment]
Same issue is also present in the quotes module

**Comment by meierwitt** [comment]
In 7.9.2 the invoice is not showen as attachment but is send with the email.
