### ISSUE TITLE
7.9.3 Cant send Emails Out

### ISSUE THREAD

**Issue by petedyer** [salesagility/SuiteCRM#3904]
7.9.3

Since upgrade cant send any messages out. The following appears in the log file User xxx attempted to send an email using incorrect email account settings in which they do not have access to. This didn't happen in 7.9.2

**Comment by pgorod** [comment]
I think (not 100% sure, though), that there is a change requiring individual users to send email via their own accounts, instead of allowing a system account like before. So maybe you can check if that user's Email configurations.

**Comment by sergio91pt** [comment]
Are you trying to send email through a personal account? Try to re-enter the outbound settings, as if your account was linked to a non-existent outbound account (or removed), you'll get that message (#3812  - SCRMBT-20).

**Comment by petedyer** [comment]
Hi no its not the personal account its a set of three different outbound accounts. Cant send any emails with them. Gone back in and edited and saved them but not getting any further. Only occurring since last nights update

**Comment by pgorod** [comment]
@petedyer where exactly did you define the settings for those accounts?

**Comment by Mausino** [comment]
@petedyer  has your issue something with #3901 ???

**Comment by petedyer** [comment]
I've attached a screenshot. Group settings are done via group settings. Outbound via the outbound. Then from profile(admin user in this case) allow access to the three group emails.
![email-screenshot-issue](https://user-images.githubusercontent.com/17161452/28321906-76568636-6bcc-11e7-890c-ffaab207be63.jpg)
 Note this is a system thats not a clean install but one weve been upgrading every since early days of suite(in case this makes a difference)

**Comment by petedyer** [comment]
Hi @Mausino  we are using mysql and no we do get the group emails appearing the from dropdown so this doesn't happen to us

**Comment by petedyer** [comment]
Is it something to do with the security in  terms of the fact these three are group accounts and appear in the from compose field BUT these three are not set in the outbound settings(well one is)

**Comment by petedyer** [comment]
Hi #pgorod are we not meant to be using outbound accounts but using individual accounts to send out out email - bit confised here so can someone kindly clear this up.

**Comment by halest** [comment]
FYI, I had to comment out the whole `$this->userIsAllowedToSendEmail` function on EmailController.php Line 149 (changed it to `if (1===1)` ) to get it so send mail for the moment, otherwise it would just time out on the ajax-dialogue

**Comment by petedyer** [comment]
@halest  thats sorted the issue for now. We just returned true from the function    protected function userIsAllowedToSendEmail($requestedUser, $requestedInboundEmail, $requestedEmail)

line 802 if anyone else needs to do it for now

**Comment by petedyer** [comment]
thanks @halest by way

**Comment by halest** [comment]
@petedyer You're welcome :)

**Comment by Dillon-Brown** [comment]
@petedyer @halest 

Can you confirm if you have this checkbox ticked?
![issue-3904](https://user-images.githubusercontent.com/26431166/28366556-243c38c8-6c85-11e7-885c-51c3ea864723.png)

**Comment by petedyer** [comment]
Hi Dillion how do I get to that screen? I cant seem to locate the exact screen you are looking at

**Comment by halest** [comment]
@Dillon-Brown  I do not see that option
[Image](https://img1.picload.org/image/rpwraiia/nope.png)

**Comment by petedyer** [comment]
![screen-capture-email-issue](https://user-images.githubusercontent.com/17161452/28366951-b247f174-6c86-11e7-92ca-7ab97a8a74e4.jpg)

**Comment by petedyer** [comment]
Okay I located it and the box is ticked

**Comment by petedyer** [comment]
@halest its the screen from the group edit email

**Comment by petedyer** [comment]
from this url /index.php?module=InboundEmail&action=index

**Comment by halest** [comment]
I still did not see these options until I created a new Group-Account? Is that supposed so?

**Comment by petedyer** [comment]
sorry don't know my accounts were already there from a previous install. Have you created a new group account and tested that

**Comment by samus-aran** [comment]
Hi Guys,

@halest - Not quite sure about that strange you are unable to see those additional fields.

Regards to the current issue we'll investigate it as the additional Security check is obviously affecting your set up. Set this as a bug/High Priority and update accordingly.

**Comment by petedyer** [comment]
@samus-aran  just a quick flick through the method shows hasAccessToInboundEmailAccount is true
but isAllowedToUseOutboundEmail is always false it never meets the conditions. This is under method userIsAllowedToSendEmail  line 800

**Comment by petedyer** [comment]
@samus-aran  also line 848 if($outboundEmailAccount->isAllowUserAccessToSystemDefaultOutbound()) 
this is never true

**Comment by samus-aran** [comment]
Hi @petedyer 

Have you debugged this? Reason why I'm asking is that it sounds like your $outboundEmailAccount is going into the 'system'  IF condition where in the my scenerio any Group Email Accounts I create (via Admin > Inbound Emails) have been 'user' types which should be set to 'true'.

**Comment by samus-aran** [comment]
Also just to provide more insight, the function 
if($outboundEmailAccount->isAllowUserAccessToSystemDefaultOutbound()) {
                $isAllowedToUseOutboundEmail = true;
            }

Actually checks if the System Email Settings Allows Users to send emails from it.

https://github.com/salesagility/SuiteCRM/blob/master/include/OutboundEmail/OutboundEmail.php#L368

So that is basically this Tickbox here.  If this is NOT ticked then it will return false

![email_settings](https://user-images.githubusercontent.com/4041275/28368822-9cfbdfe0-6c8d-11e7-9f89-84d40b7dd75b.png)

**Comment by petedyer** [comment]
Hi Guys I'm getting confused my screenshot looks different to @samus-aran but has the tick box

**Comment by halest** [comment]
I've now seen about 3 or 4 different layouts in that module. So I don't know any more either

**Comment by petedyer** [comment]
Hi yeah its a system group email that an administrator is using to send out email. What should be the relevant checkbox in the database I can check to see if its populated correctly

**Comment by petedyer** [comment]
@halest lol glad its not just me going loopy

**Comment by samus-aran** [comment]
No Problem guys :)

The database table you are looking for is:

'config'

And the row should be category 'notify', name 'allow_default_outbound' and the value SHOULD be 2.

Hope that helps.

**Comment by samus-aran** [comment]
Ok @petedyer and @halest 

Just want to hopefully clarify things on our side.

@halest 
Your Group Account Emails (all three of them), are you using the System's Email Settings Account as the Outbound Email or a Personal Outbound Email account?
https://github.com/salesagility/SuiteCRM/issues/3904#issuecomment-316336555

Why? Its because the System Email Settings must allow users to be able to send out emails (using that tick box in my previous comment).  You may need to ask your Admin to confirm that if you are unable to see it. This piece of security was added in 7.9.3.

@petedyer is that the same set up for yourselves? You used the SuiteCRM System's email to send out all emails and not personal outbound accounts?

**Comment by halest** [comment]
@samus-aran I see this option on the newly created Group-account but not on an older one from 7.7.x. And of course I don't see it on a personal account. Checking the box and saving only brings me to a white screen though, BUT:
I have commented out the whole permission-thing as described above and am personally fine with that. I never had a plan to prohibit my users from sending mails anyway.

**Comment by samus-aran** [comment]
The 'Allow Users to use this account in outgoing emails' is ONLY visible on the single system Email Settings.  You would access the below screenshot via 'Admin Panel > Email Settings'.  That checkbox doesn't appear for Inbound or Outbound Email accounts via 'Admin Panel > Inbound Email' or 'Admin Panel > Outbound Emails'.  Does that make sense?

I completely understand you are happy with your solution, but it would be great if we can ask a little more as we just want to ensure that if others are experiencing this that we can replicate it knowing the use case scenario :smile:  

I'm certainly interested in the white screen issue :fearful: Where is that happening? Can you provide steps?

**Comment by halest** [comment]
Sure, 
to me it's just 
1) open inbound account-list
2) Click the pen on an group-account
3) Set the checkbox
4) Save
5) White screen
More Info:
The POST returns 200.

Stacktrace is

`Wed Jul 19 17:27:14 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT * FROM folders WHERE parent_folder = "7a80298e-c1ee-1f95-568d-57fe1e7d37dc"::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name '7a80298e-c1ee-1f95-568d-57fe1e7d37dc'.
Wed Jul 19 17:27:14 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT * FROM folders WHERE parent_folder = "da351aa3-92ee-2597-16da-596f52957415"::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'da351aa3-92ee-2597-16da-596f52957415'.
Wed Jul 19 17:27:14 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT * FROM folders WHERE parent_folder = "cf6ef38c-97bb-142b-cb98-5950ec069e73"::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'cf6ef38c-97bb-142b-cb98-5950ec069e73'.
Wed Jul 19 17:27:14 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT * FROM folders WHERE parent_folder = "b12d3cb3-5447-62b8-5e72-578743c88577"::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'b12d3cb3-5447-62b8-5e72-578743c88577'.
Wed Jul 19 17:27:30 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:SELECT id FROM folders WHERE folders.id LIKE "da351aa3-92ee-2597-16da-596f52957415"::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'da351aa3-92ee-2597-16da-596f52957415'.
Wed Jul 19 17:27:30 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL]  Query Failed:INSERT INTO folders(id, name, folder_type, parent_folder, has_child, is_group, is_dynamic, dynamic_query, assign_to_id, created_by, modified_by, deleted) VALUES(N'da351aa3-92ee-2597-16da-596f52957415', N'INBOX (Gruppenaccount)', N'inbound', '', 1, 0, 1, '', '', N'9b275f6c-27fd-1548-4764-577e2cb4df0f', N'9b275f6c-27fd-1548-4764-577e2cb4df0f', 0)::: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of PRIMARY KEY constraint 'folderspk'. Cannot insert duplicate key in object 'dbo.folders'. The duplicate key value is (da351aa3-92ee-2597-16da-596f52957415).
[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The statement has been terminated.
Wed Jul 19 17:27:30 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL] Exception handling in C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php:397
Wed Jul 19 17:27:30 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL] Exception in Controller: Datenbank Fehler. Bitte sehen Sie in der Datei suitecrm.log nach.
Wed Jul 19 17:27:30 2017 [4244][9b275f6c-27fd-1548-4764-577e2cb4df0f][FATAL] backtrace:
#0 C:\inetpub\suitecrm\include\database\DBManager.php(345): sugar_die('Datenbank Fehle...')
#1 C:\inetpub\suitecrm\include\database\DBManager.php(321): DBManager->registerError(' Query Failed:I...', ' Query Failed:I...', true)
#2 C:\inetpub\suitecrm\include\database\SqlsrvManager.php(227): DBManager->checkError(' Query Failed:I...', true)
#3 C:\inetpub\suitecrm\include\SugarFolders\SugarFolders.php(1071): SqlsrvManager->query('INSERT INTO fol...', true)
#4 C:\inetpub\suitecrm\modules\InboundEmail\Save.php(288): SugarFolder->save()
#5 C:\inetpub\suitecrm\include\MVC\View\SugarView.php(791): include_once('C:\\inetpub\\suit...')
#6 C:\inetpub\suitecrm\include\MVC\View\views\view.classic.php(74): SugarView->includeClassicFile('modules/Inbound...')
#7 C:\inetpub\suitecrm\include\MVC\View\SugarView.php(199): ViewClassic->display()
#8 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(427): SugarView->process()
#9 C:\inetpub\suitecrm\include\MVC\Controller\SugarController.php(370): SugarController->processView()
#10 C:\inetpub\suitecrm\include\MVC\SugarApplication.php(105): SugarController->execute()
#11 C:\inetpub\suitecrm\index.php(52): SugarApplication->execute()
#12 {main}`

**Comment by petedyer** [comment]
Hi @samus-aran  sorry been away from computer. Yeah its the group outbound emails as I'm accessing these from the outbound screen. Ill check the db in a moment

**Comment by petedyer** [comment]
@samus-aran That flag isn't 2 on mine however reading your last post and by going to 'Admin Panel > Email Settings I see a checkbox. Ill try this to see if it improves the situation

**Comment by petedyer** [comment]
@samus-aran Setting the flag from the screen  'Admin Panel > Email Settings' as done the trick.
So does this mean the flag from the group email is redundant or is it the second stage of the security check(eg someone wont be able to send out from group if they haven't even got the first checkbox ticked)

**Comment by petedyer** [comment]
@halest does the above sort your sending issue out?

**Comment by samus-aran** [comment]
Hi @petedyer

The flag in the Group Email isn't a security check so no that was a red hearing on my part.

Regards to the Group Emails, the ability to send emails from them is all down to the Outbound Account associated to them which can only be the system Email Account i.e. Admin > Email Settings.  So yeah that was the security fix itself that checkbox needs to be in place as Group Email Account rely on it.

**Comment by samus-aran** [comment]
So @petedyer and @halest 
We believe we have established the issue? That since the upgrade there was an additional security check made that allow users to use group accounts accordingly to the Admin > Email Settings?  This is something we should make more clear to the users and the Release Notes.

If you are happy we have resolved the issue (either by removing the check or applying the true) can we close this issue?

@halest Can we make a new issue regarding to your white error screen?

**Comment by gymad** [comment]
I added a commit in PR #3921 which refactored the method EmailsController.php::userIsAllowedToSendEmail() and contains a possible fix for this issue but this function call the InboundEmail::isGroupEmailAccount() which function also fixed in my PR #3914, So probably that PR related to this issue also.

**Comment by halest** [comment]
@samus-aran First question: Yes on my end.
Second question: I have a similar issue in #3919 , which in my opinion stems from the fact that the created SQL query uses double quotes which on MSSQL compares to another column. My guess is it should work with double quotes

**Comment by sergio91pt** [comment]
Right now it's not possible to assign an outbound account to a group inbound account #3865 through the UI. The Outbound Emails section in the administration settings only creates or modified accounts, it doesn't associate them, so most likely all group emails are going through the system account.
It is possible to associate by hand in the database, but it is error prone as it involves editing php's serialized  output.

**Comment by petedyer** [comment]
Hi @samus-aran  yes in my case the issue is resolved and the reasons are clear. From my point of view this ticket can be closed

**Comment by lou-diamonds** [comment]
Ok, my email is not working & this is the only result that comes up for "attempted to send an email using incorrect email account settings in which they do not have access to." in Google.

I still get this error in my suitecrm.log.

After upgrading to 7.9.4 I can't send any email & I can't figure out how to get it to work again. Any help will appreciated. 

I'm new so please forgive me, but I'm not clear on what the solution is from the above thread. Can someone help me trouble shoot this?

**Comment by Dillon-Brown** [comment]
@lou-diamonds Are you using the System's Email Settings Account as the Outbound Email or a Personal Outbound Email account?

The System Email Settings must allow users to be able to send out emails .This piece of security was added in 7.9.3 #3812. You can find the option to enable this under "Admin Panel -> Email Settings -> Allow Users to use this account for outgoing email"

![28368822-9cfbdfe0-6c8d-11e7-9f89-84d40b7dd75b](https://user-images.githubusercontent.com/26431166/28601080-1adb00e2-71ae-11e7-8886-04a928c3dd1d.png)

**Comment by Mausino** [comment]
@Dillon-Brown  On our site is working fine.. without any issue.. problem is with group inbound emails... which we getting issue: Error sending Email. Please contact your Administrator... but this belong to other issue.. i am not sure to which because it to many issues with inbound group emails :)

**Comment by lou-diamonds** [comment]
Thanks for the responses guys! I can send the test email fine, but nothing from the compose email screen. When I send from that screen, I get the "Error Sending Email. Please contact your administrator for assistance." message from the compose email screen. And my suitecrm.log says "[SECURITY] User x attempted to send an email using incorrect email account settings in which they do not have access to."

@Dillon-Brown I've tried it both with the system email & with the users email.  Here is the system email screen:

![sc3](https://user-images.githubusercontent.com/30443202/28619807-326c35d0-71d8-11e7-97df-115e1f763871.png)

Then here are that user's settings:

![sc2](https://user-images.githubusercontent.com/30443202/28619820-470bc032-71d8-11e7-9ffa-fb268192cf65.png)

@Mausino Here are my group settings:

![sc4](https://user-images.githubusercontent.com/30443202/28619833-61ee987a-71d8-11e7-80c5-52d47d0cdf4d.png)

Any suggestions would be greatly appreciated!

Thanks!

**Comment by Nico90** [comment]
I have the same problem of @lou-diamonds and I am running SuiteCRM 7.9.7. My log says [SECURITY] User Administrator attempted to send an email using incorrect email account settings in which they do not have access to.

Does anyone find a solution?

**Comment by lou-diamonds** [comment]
@Nico90 Sorry for the late response my friend, but I had to revert back to my previous installation & then I upgraded to the LTS version. That allowed me to upgrade without that issue. Hope this helps.

**Comment by Nico90** [comment]
I installed SuiteCRM version 7.8.8 and Email Module is working fine. Thanks Nico
