### ISSUE TITLE
Alert link broken

### ISSUE THREAD

**Issue by uvainternational** [salesagility/SuiteCRM#4160]
#### Issue

When the Alert is notified for meeting, once click the link is directed to a page not existed, the problem is due to the additional "amp;" in the link "index.php?action=DetailView&amp;module=Meetings&amp;record=".
#### Expected Behavior

The link is supposed to redirected to "index.php?action=DetailView&module=Meetings&record=" without the additional "amp;" in the link.
#### Steps to Reproduce

1. Create a meeting schedule and wait for the Alert to be notified
2. You will see the desktop notification is prompted if you active it as well as the Alert on the to right corner.
3. Click on the desktop notification, the meeting page will show
4. Click on the Alert, the page is not existed.

#### Context

The Alert is only partly function since the link is dead.
#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 60.0.3112.101 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Linux

**Comment by pgorod** [comment]
@uvainternational Please edit your Issue to use backticks in your code instead of quotes, so that everything is properly formatted and every character shows correctly like `this`. Otherwise the difference between the correct link and the wrong link isn't even showing. Thanks for reporting.

**Comment by geconly** [comment]
This seems to be an issue with the action=redirect part of the link:
/index.php?module=Alerts&action=redirect&record=203d1608-9cac-5408-2793-5a610d76bf6a
the redirect adds the inappropriate `&amp;`

**Comment by geconly** [comment]
Changed line 125 of  modules/Alerts/controller.php to:
`    public function action_redirect()
    {
        $bean = BeanFactory::getBean('Alerts', $_GET['record']);
        //bug #4160 $bean->save(); adds &amp; to the URL
        $url = $bean->url_redirect;
        $bean->is_read = 1;
        $bean->save();

        if(empty($bean->url_redirect)) {
            if (!empty($_SERVER['HTTP_REFERER'])){
                SugarApplication::redirect($_SERVER['HTTP_REFERER']);
            }
            SugarApplication::redirect('index.php');
        }


        SugarApplication::redirect($url);

    }
`

**Comment by pgorod** [comment]
@geconly thanks for the tip!

Can I give you a few GitHub tips?

To include code with syntax highlighting, insert in triple backticks like this

    ```php
    (code)
    ```

And to illustrate a change in that file, I suggest going to the file (in the appropriate branch)

https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Alerts/controller.php

and clicking the "Pencil" icon to edit it and save. The changes will be in a copy in your own fork, and then you can create a PR (Pull Request) when you're ready to ask for them to be incorporated into SuiteCRM.

**Comment by geconly** [comment]
Super cool.

**Comment by pgorod** [comment]
Ok, then you would have to leave us the URL to your changes here, so we can check it... 

I found it in your repo: https://github.com/geconly/SuiteCRM/commit/4c8a854295ceb07e2e9b77eb4f48e1482ded7dee

Or you can just go ahead and make a PR against `SalesAgility/hotfix` branch, that way it appears here and can be assessed, approved and merged. To do this, you go into your new branch (GitHub created one for you automatically when you edited the file), here

https://github.com/geconly/SuiteCRM/tree/patch-1

and click `Pull Request`, change the `base` branch to `hotfix` and fill in the description, and hit `Create pull request`.

(I am just going through the basics of Github for you, I haven't assessed or tested your code... maybe others can say what they think of it)

**Comment by connorshea** [comment]
Assuming the previous comment is true, this has been fixed.

**Comment by anil2030** [comment]
This is still an issue in SuiteCRM 8.1.  The "Accept this meeting" link in emails received for meeting reminders has a //index.php and the double amp breaks the link.  Changing the function public function action_redirect() suggested above does not resolve this issue.
