### ISSUE TITLE
DetailView of Emails do not display the To information

### ISSUE THREAD

**Issue by isleshocky77** [salesagility/SuiteCRM#4517]
#### Issue

After importing an email, the DetailView of the email no longer displays who the Email was To. The data is contained in the database; however, does not get populated.

#### Expected Behavior

After Importing an Email you expect to see who the email was "To".

#### Actual Behavior

After Importing an Email the "To" row is blank

#### Steps to Reproduce

1. Open an Email in the Emails module 
** Note in this case, the email was To two different emails.
2. Import the Email and associate it with an Account
3. Look at the page which is now open (DetailView of the Email)
4. Notice the "To" row is empty

#### Context

Unable to see who an Email which is associated to an Account/Lead/Contact was sent To

#### Your Environment

* SuiteCRM Version used: 7.97
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 62.0.3202.62 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by e-reeley** [comment]
Hi @isleshocky77 , sorry that this comment remained unanswered for this length of time.
I believe this issue has been fixed at #4672.

It seems that there was a second issue opened for the same problem.

Is this the correct fix for your issue?

**Comment by isleshocky77** [comment]
@e-reeley It looks like I'm currently running v7.9.8 which includes that patch (I double-checked the file) and it would appear that it doesn't fix the bug described in this issue - as it's still not working.

Just a side-note, I didn't dig into the code too much, but that issue (#4667) touches code for the MyEmailsDashlet, where this bug specifically is about the DetailView, is it possible that the same thing is happening? And he should have solved his issue by setting the variable rather than using a different one? Otherwise the other variable will have to be changed throughout other views.

**Comment by e-reeley** [comment]
@isleshocky77  sorry about that, it looked to be a similar issue, which I think as you mentioned it may be somewhat related.

Thank you for responding, I will take a look in to both issues and see if there would maybe be a more general solution for both as opposed to 2 seperate ones which I think is what you have hinted at?

Thanks for your input with this issue.
