### ISSUE TITLE
Date parameters in AOR Reports are not updated

### ISSUE THREAD

**Issue by mugge6** [salesagility/SuiteCRM#5111]
#### Issue
Date parameters on AOR reports will be lost after updating the report. This behaviour only exists if the date parameter is not the first parameter in the list, and if the parameter type is "Date".

#### Expected Behavior
Multiple date parameters should work independent from their order in the parameter list

#### Actual Behavior
After clicking the "Update" button on the report the selected parameters with type "Date" will be lost, and the report will not show the expected results. 

#### Possible Fix
Problem is in the file modules/AOR_Reports/aor_utils.php on function requestToUserParameters() on line 94ff. The following code part will use in case of the parameter type is "Date" the parameters with index 0 until 3. This is only true, if there is only one date parameter and only if this parameter is in the first position. Otherwise the index will be different.

```
if ($_REQUEST['parameter_type'][$key] === 'Date') {
       $values = array();
       $values[] = $_REQUEST['parameter_value'][0];
        $values[] = $_REQUEST['parameter_value'][1];;
        $values[] = $_REQUEST['parameter_value'][2];;
        $values[] = $_REQUEST['parameter_value'][3];;
        $params[$parameterId] = array(
               'id' => $parameterId,
               'operator' => $_REQUEST['parameter_operator'][$key],
               'type' => $_REQUEST['parameter_type'][$key],
               'value' => $values,
        );
 }
```

Possible quick fix could be using an index or shift value to calculate the correct parameter position in the parameter value array. The clean solution would be to pass the parameters with a better naming convention.

#### Steps to Reproduce
1. Create a new report.
2. Add some fields to the report.
3. Add at least 2 conditions to the report.
3.1. Create first condition with type "Value". Check the "Parameter" checkbox.
3.2. Create second condition with type "Date". Check the "Parameter" checkbox.
4. Save this report.
5. Go to detail view and set the parameters.
5.1. Set the parameter from the first condition to any value.
5.1. Set the parameter from the second condition to type "Date" and select the values for example "Now -> - -> 8 -> Months".
<img width="1104" alt="before_update" src="https://user-images.githubusercontent.com/16953779/35862907-9166834c-0b4d-11e8-8927-5a07d8c06812.png">

6. Click on "Update" Button.

7. Previously selected parameters are not selected anymore and not used on the results of the report.

<img width="1088" alt="after_update" src="https://user-images.githubusercontent.com/16953779/35862961-bffbb3f8-0b4d-11e8-84df-8b5ad6c0a2f3.png">

#### Context
Creating reports with several dates as parameters are not working. Date parameters on another position than the first one won't work as well.

#### Your Environment
* SuiteCRM Version used: 7.9.11
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1

**Comment by PedroErnst** [comment]
Thanks @mugge6 

I think this is the same issue as #5073, can you confirm? If so it is already solved in #5090

**Comment by mugge6** [comment]
If tested this issue again with a fresh SuiteCRM installation with your hotfix from #5090 and it's still reproducible. 

It looks exactly as I've described, that the index always starting by 0 with field type "Date"
![grafik](https://user-images.githubusercontent.com/16953779/35913173-2206cb8a-0bff-11e8-9d6f-05fa2046d40b.png)

In that case this issue is different as #5073, because I have no blank page.

**Comment by PedroErnst** [comment]
Yes, upon closer inspection it was not really related to the other issue.

Thanks!

**Comment by gunnicom** [comment]
Maybe it is somehow related to https://github.com/salesagility/SuiteCRM/pull/1710

**Comment by PedroErnst** [comment]
I think so, but the other issue is already fixed right?

**Comment by gunnicom** [comment]
#1710 is not fixed. I closed it because i could not reproduce it later, but maybe that was because date parameter was in first place or something like that. Maybe reproducible with different order.

**Comment by mugge6** [comment]
I've tested your fix #5126, it's working on my side. Thanks!

**Comment by jannepesonen** [comment]
For me this is not working. Testing version 7.9.12 and #5126 fix.
Custom modules date field.
If using 1 date field and period conditions then it works, I can change period e.g. from this week to last week (if I first correct period end dates, else 1 week is 8 days #5129).
But if using value conditions and 1 or 2 date fields, then it is not working can not make changes.

**Comment by PedroErnst** [comment]
@jannepesonen 

Thanks for the feedback. Did you repair and rebuild?

**Comment by jannepesonen** [comment]
@PedroErnst 
Yes I did. I try to use now files from your both commit,
aor_utils.php and report.tpl from 1. commit and
AOR_Report.js, aor_utils.php and report.tpl from 2. commit.

Files from 1. commit works like I described previous message,
but files from 2. commit the UPDATE button don't work.

**Comment by PedroErnst** [comment]
I'm not sure if I understand you correctly, do you mean to say you're just copying the files manually over?

In that case it might not work, because if there have been commits by other people on the same file the content would not necessarily be consistent (and we've had a few merged PRs related to AOR Reports recently).

So I'd suggest you either use git to pull from the branch including all the relevant previous changes, or maybe wait for this to be included in a release.

**Comment by jannepesonen** [comment]
I use git, files are identical if I use raw files from browser.
Still same result, 2. commit files (report.tpl?) breaks update button.
When update button don't work, it is difficult to test date field parameter changes.

**Comment by PedroErnst** [comment]
@jannepesonen 

I just tested again and it seems to work ok.

Please note that the base branch for the PR is 7.8.x and not 7.9.x

**Comment by jannepesonen** [comment]
@PedroErnst 
In version 7.9.12 it doesn't work.
Tested this time in my macbook and mamp, previous test was centos.
If using periods type it works (like it works in original 7.9.12), if type is something else it doesn't work.

It may work in version 7.8.x, I don't have tested that.
There was new version 7.9.14,
not yet tested that but I don't see any mention fixing that in release note
(not in 7.9.13 or 7.9.14).

But if I wasn't clarified my problem closely enough.
Problem is not date conditions order.
Problem is when using condition in date field, if condition type is period then I can update value.
But if type is something else than period, then update don't work.
There is also different problem in period like I described in #5129 but I guess it is other story.

**Comment by PedroErnst** [comment]
@jannepesonen 

Yes in 7.9.12 it wouldn't work, as I said the proposed fix is branched off 7.8.x.

Note that also it isn't yet merged, so in 7.9.14 there problem will most likely still persist.
