### ISSUE TITLE
Can't create new Target List in 7.10.4

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#5702]
#### Steps to Reproduce
1. Open Target Lists module
2. Click `Create target list` on the sidebar or top menu
3. The first time you do this, you get the white modal box saying `An error has occurred`, `There was an error processing your request, please try again at a later time.`
4. The next time you try (until you refresh the list view) nothing happens when you click to create Target list.

Another user on the forums mentioned this as appearing when adding Contacts to a Target List from the Contact's List view (can't add).

#### Your Environment
* SuiteCRM 7.10.4 on the live demo

**Comment by pgorod** [comment]
Note that there are two failing actions in this Issue, I am hoping they are dependent on one single bug.

1. Creating new Target list
2. Adding contacts to Target list

And there is a third one which is reported like this on the [forums](https://suitecrm.com/suitecrm/forum/feedback/18570-assign-contacts-to-target-list#63625):

`when start the campaign wizard of newsletter in the second step on wizard you select the target list of the campaign
but when the wizard finish it put error on target list`

So I suggest that when we have a fix for the first issue, we test to see if the others are solved or not.

**Comment by Dillon-Brown** [comment]
Confirmed as an issue in 7.10.4. All mentioned issues have been fixed in this PR: #5688

**Comment by afatac** [comment]
Tested the fix for 7.10.4

Click **Create Target List** at location 1 does not work. Error message still shows up.

Click **Create** at location 2 works. 

See the linked image at [https://i.imgur.com/rPlXlPV.png](url)

**Comment by Jawn78** [comment]
I am experiencing the same issue running 7.10.4, while we await an update, is there a quick fix on this?

**Comment by Dillon-Brown** [comment]
@Jawn78 The provided fix here should work: #5707

**Comment by Jawn78** [comment]
Thank you! I should have read the thread better. Worked like a charm!

Now I just need to fix the google map functionality because it keeps popping up with a not found URL message. Index.php not found on this server... if you have any suggestions to a fix.

**Comment by rmunoz10** [comment]
I am experiencing the third issue described by @pgorod for email campaigns.

when start the campaign wizard for email type in the second step on wizard you select the target list of the campaign but when the wizard finishes it displays an error “You cannot send a marketing email until your target list has at least one entry. You can populate your list after finishing.”

Has this issue been fixed? Anything I'm missing?
Thanks

**Comment by rmunoz10** [comment]
Sorry, forgot environment: v.12.5 / ubuntu 20.04

I am experiencing the third issue described by @pgorod for email campaigns.

when start the campaign wizard for email type in the second step on wizard you select the target list of the campaign but when the wizard finishes it displays an error “You cannot send a marketing email until your target list has at least one entry. You can populate your list after finishing.”

Has this issue been fixed? Anything I'm missing?
Thanks
