### ISSUE TITLE
[inbound emails] folder management - Selecting --None-- breaks folders list

### ISSUE THREAD

**Issue by tech-ch1** [salesagility/SuiteCRM#5757]
When configuring a profile's email parameters, in the General tab, Folder Management group, selecting (clicking) the '--None--' entry permanently empties the folders list and breaks personal email account listing.

#### Expected Behavior
Clicking on '--None--' should leave the other entries so that we can select other folders back.

#### Actual Behavior
Clicking on '--None--'  permanently empties the folders list and breaks personal email account listing.

#### Steps to Reproduce
1. Create an inbound email account, save.
2. Go back to the profile email parameters, General tab, click on '--None--'
3. Other options are now gone.
4. Reload page, go back to the profile email parameters, Mail Accounts tabs,
5. Instead of showing the list of accounts, it shows 'Data error.'

#### Your Environment
 * SuiteCRM Version used: 7.10.4
 * Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 58
 *  Environment name and version (e.g. MySQL, PHP 7): PHP 7.2
 *  Operating System and version (e.g Ubuntu 16.04): Debian 9.4

**Comment by tech-ch1** [comment]
I've dug a bit into the code and database. It looks like the subscriptions entries have been removed from the folders_subscriptions table when I clicked on the '--None--' option. 

The folders list in folders management is retieved through a call to `retrieveFoldersForProcessing`, which executes `SELECT f.id, f.name, f.has_child, f.is_group, f.is_dynamic, f.dynamic_query, f.folder_type, f.created_by, f.deleted FROM folders f LEFT JOIN folders_subscriptions fs ON f.id = fs.folder_id LEFT JOIN inbound_email i on i.id = f.id WHERE f.deleted != 1 AND i.deleted != 1 AND fs.assigned_user_id = 'my-user-id' AND (f.parent_folder IS NULL OR f.parent_folder = '') ORDER BY f.is_dynamic, f.is_group, f.name ASC`.
Since the subsciptions are deleted, the retrieval function raises SugarFolderEmptyException.

**Comment by tech-ch1** [comment]
Apparently, the subscriptions are deleted by the updateSubscriptions functions which is triggered automatically when the selection is changed in the folder management list. Which seems to be ok.
But, the retrieveFoldersForProcessing joins on folders_subscriptions to filter folders owned by the user.

So, the list of folders a user can subscribe to is composed of only folders he is already subscribed to.

I feel like folder created by the user should also appear in the list, and maybe, `fs.assigned_user_id = 'my-user-id'` should be replaced with `(fs.assigned_user_id = 'my-user-id' OR f.created_by = 'my-user-id')`

(In function retrieveFoldersForProcessing of file SugarFolders.php)

**Comment by LuminisIndia** [comment]
I am definitely having this problem in SuiteCRM 7.10.4. Email folder are also not shown. But I don't have any 'apostrophe' in any inbound email account. Reference: https://suitecrm.com/suitecrm/forum/developer-help/18996-where-is-view-my-emails-function. Need appreciation of a problem that already exists and hurting some users.

**Comment by Mausino** [comment]
@tech-ch1  #5852 this issue is very similar to yours

**Comment by tech-ch1** [comment]
@Mausino indeed it is. However, since group accounts and personal accounts are handled separately, I am not sure it's the same bug.

**Comment by Mausino** [comment]
@pgorod i didn't found this in

logs [FATAL] Exception in Controller: SugarFolder::retrieveFoldersForProcessing() Cannot Retrieve Folders - Please check the users inbound email settings.

at the weekend looks on it my developer... when more info.. let here more details

**Comment by tech-ch1** [comment]
It seems this bug has been solved with 7.10.5 as clicking on "none" now replenishes the list of available folders.

**Comment by LuminisIndia** [comment]
No, it is still persisting in SuiteCRM v7.10.5.  Hope the team would offer some solution very soon!

**Comment by ebogaard** [comment]
This is quite an important issue, as it makes a lot of users angry. And it isn't solvable by any hack or sensible db-query.

Once you click on this, sometimes even without, you can't switch to your sent mail or any other folder.

**Comment by fcorluka** [comment]
I am in 7.10.7 version and must say Email and Inbound accounts are horrible.
1. view all emails -- NOT WORKING, must be something in search
2. set up SUPPORT inbound  (group email, auto import, auto case creation) -- NOT SHOWN ANY EMAIL, no cases
3. set up PERSONAL inbound (only auto import) -- NOW I see all personal emails, some of my SUPPORT email and for some cases are created ,,, send new email - email is shown case not created
4. created new user -- NO EMAILS SHOWN, can not select any inbound mail accounts (the problem from this thread: ' Exception in Controller:  SugarFolder::retrieveFoldersForProcessing() Cannot Retrieve Folders - Please check the users inbound email settings.')

I am not sure what was done to emails, but this is no good.

**Comment by Mausino** [comment]
@Dillon-Brown @samus-aran should it gets some priority label? 

If you have more as one email address you start be MAD from Suite Email module for example by this one issue. I my opinion is hight priority because it can break your work in Suite with emials (you will see still only one email address and will not able to switch to other folders on listview 👎 

Also qestion.. is in listview any diferencies between inbox button  and folder icon button ??? the both do same function.. open modular window with folders.

**Comment by Dillon-Brown** [comment]
@Mausino Correct, both the inbox button and folder icon button do the same thing.

**Comment by Mausino** [comment]
@Dillon-Brown is any reason to have both buttons ? i suggesting remove one of this buttons (reason is duplicity) or change name of "Inbox" button to new name "**Switch Inbox**" which is more clearly what to do. 

_Also in my case 7.10.11also isn't working when i click on "Email setting" icon._

**Comment by brendan-pike** [comment]
This issue either was not fixed or has re-appeared, we use version 7.12.2.

Can this ticket be re-opened or do I need to create a duplicate?

**Comment by OliverFels** [comment]
Just found it in >8.0 and still there. Can someone please take care about this and provide a workaround?
