### ISSUE TITLE
Group inbound accounts are visible for admin, but aren't for users (user->settings->mail accounts

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5852]
#### Issue

 if create inbound group email accounts.. for admin are visible but for user not .... 

admin
![2018-05-09_1333](https://user-images.githubusercontent.com/5773777/39820471-2d7bc1ca-53a6-11e8-8569-4cd0db29cebd.png)

users
![2018-05-09_1309](https://user-images.githubusercontent.com/5773777/39820489-3476b336-53a6-11e8-9ba9-0485198a41b5.png)

on email listview, if you push button inbox or icon Folders
![2018-05-09_1423](https://user-images.githubusercontent.com/5773777/39820066-37b97962-53a5-11e8-9499-00c71a1fb288.png)

#### Expected Behavior

User will available see the the inbox group email accounts in their email list view 

#### Actual Behavior

Getting error message in user->settings->email accounts and in email listview (when want change email inbox)

#### Steps to Reproduce

1. Create inbound email
2. Try if is working for users

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version Chrome 56.x
* Environment name and version MySQL 5.6, PHP 7.2
* Operating System and version  Win 10 Home

**Comment by LuminisIndia** [comment]
Solution is awaited for this issue ASAP!

**Comment by boombata** [comment]
same problem here. that is working in 7.8.20 but not in 7.10.7

**Comment by boombata** [comment]
Got a fix, I have inbound emails listed now:

edit /include/SugarFolders/SugarFolders.php line 612 

from 
$folders = $this->retrieveFoldersForProcessing($focusUser);

to 
$folders = $this->retrieveFoldersForProcessing($focusUser, false);

Problem introduced by this PR https://github.com/salesagility/SuiteCRM/pull/4877/files

**Comment by Mausino** [comment]
@Dillon-Brown should this ticket get the label 7.10.10 if you added the tag "Resolved: Next Relase"

**Comment by Dillon-Brown** [comment]
@Mausino This should actually already be fixed in 7.10.8. It looks like it was just missed as the PR wasn't linked up to the issue correctly.

**Comment by aimran50** [comment]
Tried upgrading from 7.8.27  This problem still exists in Version 7.11.5 and 7.10.17

**Comment by enbyted** [comment]
This is still a problem on 7.11.10

Exact same issue and same cause.

Also, I'm not sure if it is as easy as setting `subscribed` to false in the argument as in #6183
IMHO Administrator should be able to assign any group email to user, but only that user's personal emails (i.e. non-group).  But when looking at your own profile from a normal user perspective you should not be able to subscribe to arbitrary accounts.
