### ISSUE TITLE
Cannot use parenthesis in reports

### ISSUE THREAD

**Issue by st-ives** [salesagility/SuiteCRM#5900]
#### Issue
Cannot drag and drop parenthesis when creating conditions in reports

#### Expected Behavior
Click and drag "Drop parenthesis" button into conditions to add parenthesis'.
#### Actual Behavior
Clicking and dragging the button does nothing.

#### Steps to Reproduce
1. Go to reports module
2. Create a new report
3. Add conditions
4. Click, Drag and drop "Drop parenthesis" button.

#### Context
Cannot create any reports that require conditions with parenthesis (90% of our reports). Therefore, high priority.

#### Your Environment
* SuiteCRM Version used: 7.10.4
* Browser name and version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.0.34, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.3 LTS

**Comment by PedroErnst** [comment]
Thanks for reporting @st-ives 

This issue is fixed in #5667 which is included in the most recent 7.10.5 patch.

**Comment by mruch2** [comment]
Still a problem in Google Chrome 67.0.3396.79 (Official Build) (64-bit)

**Comment by PedroErnst** [comment]
@mruch2 

Which version of SuiteCRM are you using? It seems to work fine on 7.10.6

**Comment by mruch2** [comment]
7.10.5.

I will try the upgrade.
