### ISSUE TITLE
SVG files not working in PDF Templates

### ISSUE THREAD

**Issue by Pawes** [salesagility/SuiteCRM#5994]
#### Issue

I am pretty sure it has been working previously, but when I generate a PDF e.i. for invoices, using a template that has a SVG image, the image doesn't appear on the pdf. (I have confirmed it on the online demo version as well)
#### Expected Behaviour

SVG images should be visible on PDFs.
#### Actual Behavior

 It doesn't appear  on the pdf and it reports that the pdf is corrupted. I can still view the pdf, but the image is not there and there is not even a red cross.

#### Steps to Reproduce

1. Create a pdf template.
2. Add an img tag that has a "src" attribute that points to a SVG image.
3. Click "Save as PDF" and choose the new template. 

#### Context

Should maybe be low to medium priority as not all use SVG images for their PDF creation.

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox
* Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Windows (Xampp)

**Comment by javitoron** [comment]
I had the same problem. I solved it going back to previous modules/AOS_PDF_Templates/PDF_Lib/mpdf.php version.

I think it's a problem with line 8881: 
 - New mpdf is: foreach ($this->images as $file => $info) {
 - Old mpdf was: while(list($file,$info)=each($this->images)) {

**Comment by Pawes** [comment]
Thanks for the help @javitoron, unfortunately it didn't fix it for me (I did remember to repair and rebuild).

However, I see why this might be causing an issue, as changing the old for each with the new could have some unwanted side effects. As I understand it, the old "for each" would iterate through the array and if you made any changes (i.e. to an element that the loop hadn't reached) that change would be visible when the loop reached it.
The new "for each" doesn't register these kinds of changes as it makes a copy of the array initially, and then iterates through it.
see [this SO answer](https://stackoverflow.com/questions/3304885/whilelistkey-value-eacharray-vs-foreacharray-as-key-value#answer-30429069) for an explanation.

It might useful revisit the commit that [replaces the deprecated each() functions](https://github.com/salesagility/SuiteCRM/commit/6a76b8097b260cf560bf2c7399ba2ef6507ef220) with this in mind. It would be even better to upgrade the mpdf library from the original source, as they will surely have fixed this and other issues.

**Comment by javitoron** [comment]
sorry to hear that...

Some months ago I also fixed an images' error by creating a tmp folder under pdflib folder. [https://mpdf.github.io/installation-setup/folders-for-temporary-files.html](url)... just in case it helps you.

**Comment by Pawes** [comment]
Thanks again, I just tried it. It warned that it didn't have a tmp folder in the error.log and after creating it stopped. However, still no luck with the SVG files. For now I have resorted to .png files.
I also tried: `$pdf->showImageErrors = true;`
I am not sure where these errors should appear, but I am not getting anything on the pdf, in error.log or suitecrm.log.

**Comment by ChangezKhan** [comment]
@Pawes  On SuiteCRM 7.10.14 LTS version, it is working fine. Kindly check once again and update.

**Comment by Dillon-Brown** [comment]
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.
