### ISSUE TITLE
Call email reminder

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#601]
Checking the reminder checkbox to email all invitees works as intended. 

The problem arises when you try to change the reminder time for example from 15 minutes prior to 5 minutes prior **after** you have already recieved the notification for '15 minutes' prior. In that case you will not recieve an email notification. (The popup reminder works correctly in both cases)

**Comment by willrennie** [comment]
This should have been fixed in the latest release(7.5) and is possibly also fixed in 7.4.3. Can you test and confirm?

**Comment by willrennie** [comment]
No confirmation/repsonse received since post on 22nd Jan. As noted, this should have been resolved in the latest release. Please comment if you are still experiencing this issue with reminders and we can continue investigating.

**Comment by jobvector** [comment]
Sorry for very late repsonse, tested it on 7.7.4 and is still not fixed, received only 1 reminder email
