### ISSUE TITLE
From Dropdown on Email Compose has utf-8 issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#6340]
#### Issue
it is just the display bad char in from Dropdown on Email Compose. I think there is an utf-8 issue.
![screenshot_1](https://user-images.githubusercontent.com/22373035/45881388-ae8be700-bdb3-11e8-8b08-da15bbe5c512.png)

#### Expected Behavior
It should be shown like user full name with utf-8 support.

#### Steps to Reproduce

1. Open Email Compose
2. Look at from dropdown
3. See non standard utf-8 char

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment]
Hi @dursuntosun Can you please test the proposed fix for us if this resolves your issue?
Thanks!

**Comment by dursuntosun** [comment]
Yes, it is solved my issue. Thank you.

**Comment by yylzcom** [comment]
Hi,
IMHO, I think it fix just fix the sender's display problem, but "To" still get the problem.
Please check and fix.

Best regards!

![suitecrm-to-display-problem](https://user-images.githubusercontent.com/5056797/51171425-da475580-18eb-11e9-89af-8eb7fa74702f.png)

**Comment by Dillon-Brown** [comment]
@yylzcom Can you list the steps you took to replicate this? normally if you try to send an email with a special character in the "To" address you will be prevented from doing so as it wouldn't be valid.
