### ISSUE TITLE
Leads - Relation to Campaign: Field visibility in List view not saved (always switched back to hidden)

### ISSUE THREAD

**Issue by aforrer999** [salesagility/SuiteCRM#6506]
#### Issue
When customising leads and the relation "campaign_leads" is added to the list view of leads, the column visibility switches back to hidden, even if previously saved as visible. 
No similar issue found  
It is a reproducible problem, when using Admin>Studio>leads>layout>list view. After adding the relation "campaign_leads" in the Leads List view, set the column to visible and saved the view, the column is set back to hidden after changing the record filter or sort order. 

#### Expected Behavior
When the relation campaign_leads is added in the List view in Studio (saved and deployed), the field set to visible in the column selection and saved, the column should remain visible.

#### Actual Behavior
The relation campaign_leads is not saved as visible and after changing the record filter or sort order, the column is switched back to hidden.

#### Possible Fix
Check column selection >save feature

#### Steps to Reproduce
1. Go to studio
2. Add relationship "campaign_leads" to Leads>Layout>List view (and Edit view ...)
3. Save and deploy
4. View leads
5. Select columns
6. Set relation field to visible: field is visible in list view (fine so far)
7. Modify filter OR navigate away then back to lead list view
8. The relation field has been switched back to hidden

#### Context
Medium priority

This bug prevents an important customization to be deployed in a persistent way.
#### Your Environment
*Version 7.10.9, Sugar Version 6.5.25 (Build 344) 
* Firefox 63.0.3 (64-bit)):
* LAMP Server Linux Apache, MySQL, PHP 7:
* Connected device: PC / Windows 8.2

**Comment by samus-aran** [comment]
Just to follow up. I found a similar sounding issue here
https://github.com/salesagility/SuiteCRM/issues/5794 which was resolved in 7.10.8 but the version you are using is 7.10.9. So please assist with how to replicate... perhaps a video will help?

**Comment by aforrer999** [comment]
Thanks for bringing up 5794. I thought first, the columns hide away only when they are customized fields. It turns out to be that same issue. This means either 5794 was not solved or sneaked back into the new release.

**Comment by samus-aran** [comment]
@aforrer999 Are you able to replicate this on the online demo using non customised fields? That would be fantastic if you could let us know as that is using 7.10.10 and hopefully this issue hasn't resurfaced. If it has then I'll re-open #5794.
https://demo.suiteondemand.com

**Comment by aforrer999** [comment]
Hi Ashley

 

Will try. Can you provide a login for the demo instance?

 

Cheers,
Andreas

**Comment by samus-aran** [comment]
Hi @aforrer999 

The login details for this instance are the same for any demo data for example:
username: will
password: will

or try it with sally/sally 

Thanks!

**Comment by aforrer999** [comment]
Hi

I tried to reproduce the problem in the demo instance and I can confirm that in the issue #5794 is present. Please reopen it.

 

Steps to reproduce the problem:

 

1.    Open a list view (e.g. Leads)

2.    Create 2 quick filters and save them

3.    In the list view, select column selector and set a column to visible (e.g. Leads>>Lead source)

4.    The selected column is now visible

5.    Select a different quick-filter

 

ERROR >>>> In the list view, the column set to visible under 3 is now switched back to hidden

 

Cheers,

Andreas
