### ISSUE TITLE
Email import is importing random email

### ISSUE THREAD

**Issue by JanHubert** [salesagility/SuiteCRM#6957]
#### Issue

When importing an email from our imap server to an existing case, most of the times a different email is being imported instead of the viewed one. Just saw a 12 year old email after trying to import the latest email.

#### Expected Behavior

The viewed email should always be attached to the selected case.

#### Actual Behavior

A random email is being imported and attached to the selected case.
Suitecrm.log:
`Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Saving Email with invalid From name and/or Address. Details:
From field is not set.
From-name is not set.
From address and name pair does not match to from name.
From address and name pair is invalid.
codes:1, 7, 22, 15
Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Saving Email with invalid From name and/or Address. Details:
From field is not set.
From-name is not set.
From address and name pair does not match to from name.
From address and name pair is invalid.
codes:1, 7, 22, 15
Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:15 2019 [21952][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:15 2019 [21947][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:15 2019 [21947][1][ERROR] Unable to find relationship emails_email_templates
Fri Feb 15 13:07:16 2019 [21947][1][ERROR] Saving Email with invalid From name and/or Address. Details:
From field is not set.
From address is not set.
From-name is not set.
From name is not set.
From address and name pair format is incorrect, use "from@emailaddress.org <Name of Person>" format.
From address and name pair is invalid.
codes:1, 4, 7, 10, 16, 15
Fri Feb 15 13:07:16 2019 [21947][1][ERROR] Unable to find relationship emails_email_templates
`

#### Possible Fix

--

#### Steps to Reproduce

1. Setup imap accounts
2. View email, select Import from Actions menu
3. Select 'Case' and choose an existing case and click import
4. A different email is being displayed that was attached to the selected case.

#### Context
After #4999 was fixed I want to start using the email module again. Sending email now works fine. Unfortunately importing email is not working stable. After upgrading I had to follow this advice: https://suitecrm.com/suitecrm/forum/feedback/21711-7-11-1-recoverable-fatal-error-in-email-php-on-line-4737
This fixed an issue displaying emails but still the log file is quite "rich". I am afraid the log entries look like there are multiple issues which I have not seen before. 

#### Your Environment

* SuiteCRM Version used: Upgrade from 7.10.x to 7.10.13
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): current Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 15.1 and PHP 7.0 
* Operating System and version (e.g Ubuntu 16.04): Debian 9

**Comment by pgorod** [comment]
@JanHubert that issue you mention from the Forums is fixed (properly) here: #6923

**Comment by cameronblaikie** [comment]
Hi @JanHubert , 
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. 
Thanks.

**Comment by JanHubert** [comment]
Hi @cameronblaikie ,
Yes, after updating to 7.11.3 the issue persists: I can import an e-mail to a case successfully if the email is stored in the inbox of the email account. **Trying to import an e-mail from the "Sent" folder imports a totally random email** from that inbox (i.e. not "Sent" folder). This happens for all users.

suitecrm.log:
Thu Apr  4 19:02:24 2019 [6260][1][ERROR] ImapHandler trying to use a non valid resource stream.
Thu Apr  4 19:02:24 2019 [6260][1][ERROR] ImapHandler trying to use a non valid resource stream.
Thu Apr  4 19:02:33 2019 [5222][1][ERROR] ImapHandler trying to use a non valid resource stream.
Thu Apr  4 19:02:33 2019 [5222][1][ERROR] ImapHandler trying to use a non valid resource stream.
Thu Apr  4 19:02:34 2019 [5222][1][ERROR] Saving Email with invalid From name and/or Address. Details:
Von-Feld ist nicht festgelegt.
Von-Feld-Name ist nicht festgelegt.
Von-Feld Paar; Name und Adresse-Paar stimmt nicht mit Von: von Name überein.
Von-Feld Paar; Adresse und Name ist ungültig.
codes:1, 7, 22, 15
Thu Apr  4 19:02:34 2019 [5222][1][ERROR] Unable to find relationship emails_email_templates
Thu Apr  4 19:02:34 2019 [5222][1][ERROR] Saving Email with invalid From name and/or Address. Details:
Von-Feld ist nicht festgelegt.
Von-Feld-Name ist nicht festgelegt.
Von-Feld Paar; Name und Adresse-Paar stimmt nicht mit Von: von Name überein.
Von-Feld Paar; Adresse und Name ist ungültig.
codes:1, 7, 22, 15
Thu Apr  4 19:02:34 2019 [5222][1][ERROR] Unable to find relationship emails_email_templates
Thu Apr  4 19:02:34 2019 [4756][1][ERROR] Unable to find relationship emails_email_templates
Thu Apr  4 19:02:34 2019 [4756][1][ERROR] Unable to find relationship emails_email_templates
Thu Apr  4 19:02:34 2019 [4756][1][ERROR] Saving Email with invalid From name and/or Address. Details:
Von-Feld ist nicht festgelegt.
Von-Feld E-Mail-Adresse ist nicht festgelegt.
Von-Feld-Name ist nicht festgelegt.
Von-Feld Name ist nicht festgelegt.
Von-Feld Paar; Adresse und Name-Format ist falsch, "from@emailaddress.org <Name of Person>" Format verwenden.
Von-Feld Paar; Adresse und Name ist ungültig.
codes:1, 4, 7, 10, 16, 15
Thu Apr  4 19:02:34 2019 [4756][1][ERROR] Unable to find relationship emails_email_templates

Any hint would be highly appreciated!

**Comment by jdberkowitz** [comment]
I am having the same issue working in 7.11.6 Emails module. The exact issue as described by @JanHubert with a log entry of [ERROR]  ImapHandler trying to use a non valid resource stream.

It seems to be pulling the incorrect message id when going to import the email record into any module (Contacts, Leads, Accounts, Etc..) from the "Sent Emails" folder. It is reproducible from any imap account (group or personal).

Has anyone come across any fixes? It seems like a bug but perhaps is a configuration issue since it is not a widely reported problem? Any help would be greatly appreciated!

**Comment by jdberkowitz** [comment]
@JanHubert what kind of email account are you using? I'm suspecting this has to do with the Exchange server config? I'm using an AppRivier exchange lite plus account which I am not admin over.

**Comment by JanHubert** [comment]
We are using Kopano Groupware which offers plain IMAP among other protocols. I fully stopped our plan to use the email module. For over a year I tried to include shared mailboxes and SuiteCRM but I failed. Thus we will move to another solution next year.
Best of luck with your project.

**Comment by jdberkowitz** [comment]
Well that is discouraging however I will share updates as I get make them. I think my issue is do incorrect configuration of exchange and amazon SES at this moment.

Thank you,


Joshua Berkowitz

Manager/Developer

JB Designs

p:

(305) 741-5708

a:

Ft Lauderdale, FL 33312

w:

www.joshuaberkowitz.us<http://www.joshuaberkowitz.us/>  e: info@joshuaberkowitz.us<mailto:info@joshuaberkowitz.us>

Digital Development Solutions

________________________________
