### ISSUE TITLE
Popup select All records btn hidden in SuiteCRM 7.11.x

### ISSUE THREAD

**Issue by avenger33** [salesagility/SuiteCRM#7162]
#### Issue

When open popup window to select multiple records does not appear "Select This Page" and "Select All" buttons

#### Expected Behavior

The buttons "Select This Page" and "Select All" should be visible and clickable
#### Actual Behavior

The buttons "Select This Page" and "Select All" does not appear
#### Possible Fix

in ./include/ListView/* files fix templates for this buttons. 
Many of files in this folder contain string like `<label class="hidden glyphicon bootstrap-checkbox glyphicon-unchecked"><span class='suitepicon suitepicon-action-caret'></span></label>`

The label has class "hidden", when js code try to render buttons he find caret for this button, but it in label that has class "hidden". To fix it, should bring out the span tag 

#### Your Environment

* SuiteCRM Version used: 7.11.x
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All

PS sorry for my english

**Comment by dawid-zaroda** [comment]
There is lack of {$STYLE_JS} in file include/Popups/tpls/header.tpl
Commit, where this was fixed (merge bug?): https://github.com/salesagility/SuiteCRM/commit/3307bc1fd767d8a66d788f73cdebe8c6bcf7a7d8

Regards,
Dawid

**Comment by Dillon-Brown** [comment]
@dawid-zaroda Thanks! looks like this is from a merge issue with a few 7.10.x PR's still missing from hotfix.
