### ISSUE TITLE
Can't rename modules

### ISSUE THREAD

**Issue by JimMackin** [salesagility/SuiteCRM#9491]
#### Issue

Renaming modules seems to have been broken in commit c99964e86f6369560dc10d361bd5140aff26eb75

#### Expected Behavior

Renaming a module should change the modules name via the label functionality.

#### Actual Behavior

 A white screen is shown and a PHP error logged.

#### Possible Fix

Switching the references to `this` in the save dropdown function to `save` should resolve this. For a longer term fix we may want to investigate how this is called and standardise.

#### Steps to Reproduce

1. Open Admin
2. Got to "Rename Modules"
3. Attempt to switch the name of any core module
4. See the error

#### Context

Attempting to rename a module is no longer possible.

#### Your Environment

* SuiteCRM Version used: 7.12.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 96
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

**Comment by Mac-Rae** [comment]
Confirmed in latest :+1:

**Comment by adriangibanelbtactic** [comment]
After applying [@mattlorimer ](https://github.com/salesagility/SuiteCRM/pull/9496) commit manually to a Suitecrm 7.12.3 installation the module gets renamed without a problem.

So, I guess the problem is fixed.

However it shows these three lines in `suitecrm.log`file while doing the rename:
```
Wed Feb  9 19:08:07 2022 [14016][1][FATAL] Class Connectors does not exist, unable to rename.
Wed Feb  9 19:08:07 2022 [14016][1][FATAL] Class Version does not exist, unable to rename.
Wed Feb  9 19:08:07 2022 [14016][1][FATAL] Class CustomFields does not exist, unable to rename.
```
.

If you think I should open a new bug for this specific odd behaviour please complain.

**Comment by jack7anderson7** [comment]
This issue was resolve via #9496. This will be closed as a result.

Hi @adriangibanelbtactic,

If you could raise a new issue for the bug you have found, that would be very useful.

Thanks,
Jack

**Comment by bitnamiNoob** [comment]
I am using SuiteCRM version 7.12.5 and am still having the issue where it won't allow me to rename the modules.  The blank, white page is showing when selecting the option to do so.  Is there any work-around for this?

Thank you in advance!

**Comment by bitnamiNoob** [comment]
As a side note, I have verified that the mentioned config changes were already made in the new version that I am using (in the DropDownHelper.php file
